### ISSUE TITLE
Addition of a utility to be able to create differential and trend line reports using an existing repository of gatling test run results

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#100]
### Description

Addition of a utility to be able to create differential and trend line reports using an existing repository of gatling test run results

A shell script of sorts to be able to point to two or more runs and provide us with the information to be able to generate digestible HTML/CSV reports utilizing the https://github.com/nuxeo/gatling-report tool

### Motivation

It would be a good addition to the tool set, if we are able to automate the comparative analysis of a given set of gatling test run results. As part of that process, here is a small utility which can generate a differential report across two gatling test runs and a trend report for a collection of gatling results (more than 2).

The motivation for this feature request is to create a shell script which can take arguments to be consumed by the gatling-report jar file and generate us with the needed reports.

### Details

The shell script would take in arguments such as
1. location of the gatling results
2. which type of report we would like to generate : HTML, CSV
3. target directory location where these generated reports are stored

the script should be able to determine to create a differential or trend report, based on the number of simulation.log files it would be able to find within the source gatling test result directory.

**Comment by kami619** [comment]
An example on how to generate a differential report between JPA and Hot Rod Map store for Create Clients scenario:

```
$ java -jar ~/code/experiments/gatling-report/target/gatling-report-6.1-SNAPSHOT-capsule-fat.jar \
--template src/main/resources/html/diff.mustache \
~/JPAMapUndertow/createclients-20220516182100296/simulation.log \
~/HotRodUndertow/createclients-20220523125152302/simulation.log \
-o ~/reports/diffGatling/JPAvsHotRod -f
.
.
.
.
00:47:28,160 INFO  [App] Report generated: /home/kakella/reports/diffGatling/JPAvsHotRod/index.html

```

Note: the first file argument is called the Reference (JPA Map) and the second file argument is known as the Challenger (HotRod Map) 

Generated differential report in HTML format :
[JPAvsHotRod_html.zip](https://github.com/keycloak/keycloak-benchmark/files/8945886/JPAvsHotRod_html.zip)

Generated differential report in CSV format :  
[JPAvsHotRod_diff.csv](https://github.com/keycloak/keycloak-benchmark/files/8945909/JPAvsHotRod_diff.csv)

**Comment by kami619** [comment]
Another example to generate a trend line report across 3 stores (this is not an ideal case, it would be practical to obtain trend line within the same store, but with the lack of number of runs, I am show casing it this way)

```
$ java -jar ~/code/experiments/gatling-report/target/gatling-report-6.1-SNAPSHOT-capsule-fat.jar \
~/LegacyWildFly/createclients-20220516131959338/simulation.log \
~/JPAMapUndertow/createclients-20220516182100296/simulation.log \
~/HotRodUndertow/createclients-20220523125152302/simulation.log \
-o ~/reports/diffGatling/trendLines/ -f
```
Generated trend line report in HTML format:
[trendline_LegacyJpaHotRod_createClients_html.zip](https://github.com/keycloak/keycloak-benchmark/files/8945935/trendline_LegacyJpaHotRod_createClients_html.zip)

Note: we should be able to modify the mustache template to generate trends based on the long tail percentiles instead of the default avg. response time metrics used within this tool.

**Comment by kami619** [comment]
@tkyjovsk, @ahus1 : please take a look at this tool and approach and provide me any feedback you might have

**Comment by ahus1** [comment]
Looks fine to me. While the percentiles are already there for the reference/challenger, I'm looking forward to see them also in the trend diagram (we have the standard deviations there with the vertical bar, still a separate line would be nice.

From what I see here: this is valuable (even essential) to have, please continue!

Pinging @hmlnarik  and @alechenninger for this as well: To make it simpler to review for the other two, here some screenshots from the reports @kami619 created: 

Diff report Reference + Challenger

![image](https://user-images.githubusercontent.com/3957921/174856098-8259b772-bef8-4651-98a3-3454115901a1.png)

And also on the request level with a nice interactive chart: 

![image](https://user-images.githubusercontent.com/3957921/174856551-06602e70-7683-43e3-b7d1-45647f31c8bd.png)

Finally the comparison of multiple runs as a trend: 

![image](https://user-images.githubusercontent.com/3957921/174856906-05663bdb-7b21-4796-9763-f889fd1d8bb7.png)

**Comment by kami619** [comment]
thanks for the feedback, I shall continue creating a PR with the utility. I do expect to have the long tail percentile trend lines to be part of the final product such as the differential report. Good Move, to add the screenshots for easier review, appreciate the help on this :)
