### ISSUE TITLE
ROSA Cloud costs

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#1001]
https://redhat-internal.slack.com/archives/C068Z8Z3HKP/p1727743083564379
As reported by @kami619 

Update Pedro Z. with an update on cloud costs for the rest of the year and 2025

**Comment by kami619** [comment]
A case has been logged with AWS for the same. Lets see what they come back with, I have cc'ed you in the request @ahus1

**Comment by kami619** [comment]
@ahus1 based on the internal update from Red Hat, we determined our AWS account is already qualifying for the 0$ charge for all the ROSA HCP usage for the next 3 years. And we should see a refund for the same in a few weeks for the charges that were levied upon us. So closing this ticket as no action is needed further from our end and the AWS Cost forecast would remain under our budgeting thresholds for the upcoming quarter through the end of the year 2024.

**Comment by ahus1** [comment]
Thank you for looking after this, @kami619. I've redacted your previous comment as this is a public project.
