### ISSUE TITLE
Why 20k clients is so slow

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak-benchmark#1018]
Cache usage: 2x in users cache, 3x in realms cache per client. 

-> 10k clients

-> reduce RPS to a number where the DB is no longer overload -> reduce to 50% to not overload the database

-> Write some docs on how to size users and client cache based on the number of clients

Follow-up task: update the sizing guide for RHBK26

**Comment by pruivo** [comment]
Took a quick look inside the `realm` cache and it should require 4 entries per client

```
<client-uuid>.optional.clientscopes -> ClientScopeListQuery
<client-uuid>.default.clientscopes ->  ClientScopeListQuery
realm-0.client.query.by.clientId.<client-id> -> ClientListQuery
<client-uuid> -> CachedClient
```

There are other values stored in the `realms` cache as follows:
```
CachedClientRole
CachedClient
CachedGroup
CacheRealmRole
CachedCount
ClientScopeListQuery
ClientListQuery
RealmListQuery
```

I'm wondering why users got their cache but clients didn't 🤔

**Comment by pruivo** [comment]
### Nano optimizations (food for though)

* **Clients scopes could be a single entry**

A single query to fetch the default and optional scopes and store them in `ClientScopeListQuery`. Not only save 1 cache entry but 1 database access too.

* **Cache client on first access**

Clients are only cached on the second access. When the cache entry `realm-0.client.query.by.clientId.<client-id> -> ClientListQuery` is created, it does not cache the client. Why not!? It is loaded from the database and can be cached right away. The second access will cache it. 

* **The impossible change...**

The cache entry `realm-0.client.query.by.clientId.<client-id> -> ClientListQuery` could be removed if the client's UUID was generated from `realm`+`client-id`. It would break existing databases and can never be implemented 😢

**Comment by pruivo** [comment]
### Configuring Gatling to use only 10k clients

**Summary**
Using half of the client brings the DB usage to ~65% and the 99% response time to ~500ms. Cache hit ratio around ~75%

**Database Usage**
![db](https://github.com/user-attachments/assets/7e1ebe02-8ca4-4c9f-a8b9-80eb66460d0d)


**Gatling Results**
![gatling](https://github.com/user-attachments/assets/58343cf5-c20d-4867-aa12-b0cb88ec1116)


**Keycloak Response Times**
![kc](https://github.com/user-attachments/assets/c06ab70d-d4b2-4f22-921d-213662188357)


**Caches Hit Ratio**
![caches](https://github.com/user-attachments/assets/1d1f8c71-97a0-40b8-835c-e60ebf882c6b)

**Comment by pruivo** [comment]
@ahus1 @mhajas Do we want to reduce the RPS to reduce the load on the database below 50%? What is the target 99% response time that you have in mind?

**Comment by pruivo** [comment]
### 10k Client and 750 RPS (25% reduction)

**Summary**
DB usage dropped to ~50% and the 99% response time to 77ms. The cache hit ratio is ~75%.

**Database Usage**
![db](https://github.com/user-attachments/assets/398c3940-a2bf-4a20-95a4-22c7334e6eca)


**Gatling Results**
![gatling](https://github.com/user-attachments/assets/5a1652f5-94aa-4dea-9a07-a1c80917f73c)

**Keycloak Response Times**
![kc](https://github.com/user-attachments/assets/8b0c9f5d-f904-4cbc-aff7-ca5cb144bbac)

**Comment by ahus1** [comment]
Thanks, these numbers look good. Still one thing that concerns me: There is a http status code 401 there meaning access denied. This is unexpected. Can you please have a look? If there is a 401, this could mean the wrong password or the client doesn't exist or something different. This might then lead to a very different load pattern. Thanks!
