### ISSUE TITLE
Add the dataset provider to the minikube setup

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#102]
### Description

At the moment we're deploying the standard Keycloak nightly build without modifications. The dataset provider would help to test with scaled installations.

### Motivation

Adding the dataprovider to the minikube setup would allow us to prepare a database with a lot of initial entities in a Kubernetes environment.

**Comment by kami619** [comment]
looks good to me and works as expected on my local minikube setup.
