### ISSUE TITLE
enable event-metrics-user-enabled in Keycloak benchmark deployments

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#1050]
```[tasklist]
### Tasks
- [x] update the keycloak.yaml
- [x] run performance tests to see if there an overhead with and without the user event metrics
```

**Comment by ahus1** [comment]
With the large number of clients we're running here, the `clientId` dimension should probably skipped. We also don't use IDPs here. Therefore IMHO the "verify different dimensions for realm, idp, clientId" could be minimal. Also for the "make the dimension options configurable" I'm not sure if that is needed in our helm charts (except if you have a scenario where need it)

**Comment by kami619** [comment]
Performance run with user event metrics enabled: https://github.com/keycloak/keycloak-benchmark/blob/result-data/rosa_scalability/2024/11/27/result-20241127-151831-fa45da10-06e4-49ed-a1a0-d138c07e578f.json

Performance run baseline without user event metrics enabled: https://github.com/keycloak/keycloak-benchmark/blob/result-data/rosa_scalability/2024/11/20/result-20241120-091535-32c1f8f9-a728-43c7-b7dc-01ff9dff624c.json

Based on these results, I didn't observe any significant performance overhead due to the enablement of metrics.

**Comment by kami619** [comment]
I think we should deal with the rest of the updates to the docs under https://github.com/keycloak/keycloak/issues/35573 and close this task, as it has all the info needed for users to get started.

In addition to this, I will create a separate task for prototyping the dashboard for user-event-metrics, if thats ok with everyone.
