### ISSUE TITLE
Restructure the docs to a multi-page documentation site

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#125]
### Description

The documentation is currently scattered in multiple places, and the README for minikube is getting quite big and should be splitted.

This PR attempts to prepare a minimal static site using Antora. It will feature the guides style already used for Keycloak's main website, plus the versioning of docs to releases.

**Comment by kami619** [comment]
@ahus1 is there any more work still pending on this issue ?

**Comment by ahus1** [comment]
Yes, this can be closed - thanks.
