### ISSUE TITLE
Unstable deployment on cri-o

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#128]
### Describe the bug

Pods have been restarted, and are sometimes unresponsive. Needs to be investigated.

### Version

0.7-SNAPSHOT

**Comment by kami619** [comment]
Even after the time we spent on the investigation of this issue, We still seem to face a similar issue with cri-o runtime, where the services wont come up as quickly as the docker runtime and it puts the system in non-responsive state for a longer periods of time. It works eventually with inconsistencies, so it would be good for us to continue to use docker runtime for the near term and look for alternative options to narrow down on what metrics we are scraping to save on the scraping time.
