### ISSUE TITLE
Allow pacing of scenarios

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-benchmark#132]
### Description

(Note: this may be possible already by configuration, but I am not familiar with Gatling, so I apologize if I have missed something)

I would like to propose allowing pacing and random delay of scenarios so that it will help understand Keycloak performance for different expected load situations. For example, If I have 100 realms with 1000 users each, and I expect twice daily logins (username-password and code-to-token), I'd like to be able to run a scenario at that pace (a login and code flow about every .43 seconds) in order to understand performance impact of that specific scenario.

### Motivation

Allow users to specify the likely pace of their scenarios.

**Comment by kami619** [comment]
@xgp I believe that should be possible with a combination of `.nothingFor` and `SequentialScenarios` in gatling.

https://gatling.io/docs/gatling/reference/current/core/injection/#open-model
https://gatling.io/docs/gatling/reference/current/core/injection/#sequential-scenarios

Both features should be available with the gatling version we have in the project pom - https://github.com/keycloak/keycloak-benchmark/blob/main/benchmark/pom.xml#L11

Let me know, if that doesn't answer your question.

**Comment by xgp** [comment]
Hi @kami619 Thanks for sending this. I haven't had a chance to try this. I'll try `SequentialScenarios` in the next couple of days.

**Comment by kami619** [comment]
@xgp Hope you had a chance to try the `SequentialScenarios`. I am closing this ticket for now, please re-open the ticket if your findings indeed prove there is a need to enhance the scripts instead.
