### ISSUE TITLE
Provision: Collect the information about the system under test when provision/minikube is used for Keycloak perf tests

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#133]
### Description

Provision: Collect the information about the system under test when provision/minikube is used for Keycloak performance tests

We would like add a feature to the framework, to enable the capture before and after state of the various components of the system under test, Keycloak.

### Motivation

The motivation for this to alleviate any manual observation necessary to understand the state of the cluster before and after the run and automate this as much as possible and archive the observations along with the other results, metrics in the final run report generated.

Describing the system under test to track any changes in the system and make sure we have a baseline configuration to compare our test results against.

Other half of the information is to collect the behavior of the system via metrics/logs/information during and post the load simulation.

### Details

Configuration setup:
- git commit hash on the benchmark project
- git commit / version of Keycloak server

Which Components ?

- Keycloak App server
- External Database server (if used)
- External Cache server (if used)

What Component state/info ?

- Pods for a specific application
  - Restarts
  - Error logs with Exception summary 
  - Scaling during the run
  - Start and End of the run pod counts
  - Change in underlying app states
  - Resource limits (allocated CPU, Mem, Connections)
- App servers
  - Error Logs with Exception summary
  - JVM stats around Garbage Collection
  - Allocated Hashing Iterations
  - Database connection pool configuration
- Ingress Router
  - Resource limits (Connections etc.,) 
- Database
  - Database connection pool utilization, configuration
  - Query Statistics from Database such as,
    - slow logs 
    - unused indexes
    - hot indexes
    - query cache utilization
- Cache
  - Query Statistics from Cache layer (Infinispan etc.,)

**Comment by kami619** [comment]
We could also fetch the current image version information using something like this 

command:
```
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" | tr -s '[[:space:]]' '\n' | sort | uniq -c 
```

output:
```
1 astefanutti/kubebox:server
      1 docker.io/grafana/promtail:2.6.1
      1 gcr.io/cadvisor/cadvisor:v0.44.0
      1 gcr.io/k8s-minikube/storage-provisioner:v5
      1 grafana/grafana:9.0.2
      1 grafana/loki:2.6.1
      1 jaegertracing/all-in-one:1.29.0
      1 k8s.gcr.io/coredns/coredns:v1.8.6
      1 k8s.gcr.io/etcd:3.5.1-0
      1 k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de
      2 k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
      1 k8s.gcr.io/kube-apiserver:v1.23.3
      1 k8s.gcr.io/kube-controller-manager:v1.23.3
      1 k8s.gcr.io/kube-proxy:v1.23.3
      1 k8s.gcr.io/kube-scheduler:v1.23.3
      1 postgres:13.2
      1 prom/graphite-exporter:latest
      1 quay.io/cryostat/cryostat:2.1.1
      1 quay.io/cryostat/cryostat-grafana-dashboard:2.1.0
      1 quay.io/cryostat/jfr-datasource:2.1.0
      1 quay.io/keycloak/keycloak:nightly
      1 quay.io/keycloak/keycloak-operator:nightly
      1 quay.io/kiwigrid/k8s-sidecar:1.19.2
      1 quay.io/prometheus/alertmanager:v0.24.0
      1 quay.io/prometheuscommunity/postgres-exporter:v0.10.1
      1 quay.io/prometheus/node-exporter:v1.3.1
      2 quay.io/prometheus-operator/prometheus-config-reloader:v0.57.0
      1 quay.io/prometheus-operator/prometheus-operator:v0.57.0
      1 quay.io/prometheus/prometheus:v2.36.1
      1 registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0
      1 sqlpad/sqlpad:6.11.0
```

**Comment by kami619** [comment]
Another tidbit of info that can be collected would be the Minikube VM stats with below examples 

```
echo "Basic Health Check Values"
echo "CPU Stats"
minikube ssh -- top -b -n 1 | head -n 4
echo "Mem Stats"
minikube ssh -- free -m
echo "Disk Stats"
minikube ssh -- df -h /var/lib/docker
```

**Comment by ahus1** [comment]
We haven't implemented this for the last year, so I'm closing this as we probably don't need it at the moment.
