### ISSUE TITLE
Close to 7x higher Network I/O for CreateDeleteGroups scenario when compared with other Storage Area simulation such as Roles

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#141]
### Describe the bug

We observed close to 8X higher Network I/O for CreateDeleteGroups scenario when compared with other Storage Area simulation such as Roles

### Version

nightly (7/18/2022)

### Expected behavior

We would want to see lesser Network I/O in comparison with other Storage areas or at least understand the underlying reason for higher network i/o for this specific load simulation of the Groups storage area.

### Actual behavior

As pointed out in the below screenshot, the simulation, that occurred between 21:50 to 23:00 hrs EST, points out a higher network utilization by the Groups APIs during the CreateDeleteGroups load simulation.

![HigherNetworkIO_Groups](https://user-images.githubusercontent.com/3415105/180033600-0e1e53b9-7fdb-45a8-8e31-10e313d0e414.png)

Also in the screenshot are the sibling runs for scenarios, which had quite less network i/o when compared to the Groups storage area.

CreateDeleteRoles : 20:30 to 21:45 Hrs EST 
CreateRoles       : 23:09 to 00:05 Hrs EsT

### How to Reproduce?

re-run the simulation using the below parameters for CreateDeleteGroups load scenario

```
./bin/kcb.sh --scenario=keycloak.scenario.admin.CreateDeleteGroups \
--server-url=https://keycloak.{MASKED}.nip.io/ --client-secret=setup-for-benchmark \
--concurrent-users=25 --ramp-up=600 --measurement=3600 --ramp-down=600 --user-think-time=3
```

**Comment by kami619** [comment]
this issue could also be related to the fix https://github.com/keycloak/keycloak/issues/13641

**Comment by ahus1** [comment]
I @kami619 - could you please update the issue to indicate the storage we used - wasn't it the legacy store?

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
