### ISSUE TITLE
LoginUserPassword scenario fails with realm provisioned with manage_gatling_client.sh shell script

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#159]
### Describe the bug

LoginUserPassword scenario fails with an invalid parameter: redirect_uri issue with the latest Keycloak build

### Version

nightly (8/16/2022)

### Expected behavior

we should have had successful GET of the login page

### Actual behavior

however to fetch the login page the requests start to throw a 400 bad request error, with the below HTTP error

```
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Browser to Log In Endpoint: KO status.find.is(200), but actually found 400
=========================
Session:
Session(Authentication - Login Username/Password,1,Map(clientId -> client-0, email -> , gatling.http.cache.dns -> io.gatling.http.resolver.ShufflingNameResolver@2ea6a3b2, state -> 3807ec13-145b-e0b9-2b73-91b8f6aa0349, redirectUri -> https://keycloak.192.168.39.226.nip.io/realms/realm-0/account/#/security/signingin, username -> user-0, adminUsername -> null, lastName -> , firstName -> , gatling.http.ssl.sslContexts -> io.gatling.http.util.SslContexts@334e1fc4, wrongPasswordCount -> 0, gatling.http.referer -> https://keycloak.192.168.39.226.nip.io/realms/realm-0/protocol/openid-connect/auth?login=true&response_type=code&client_id=client-0&state=3807ec13-145b-e0b9-2b73-91b8f6aa0349&redirect_uri=https%3A%2F%2Fkeycloak.192.168.39.226.nip.io%2Frealms%2Frealm-0%2Faccount%2F%23%2Fsecurity%2Fsigningin&scope=openid+profile, adminPassword -> null, clientSecret -> client-0-secret, realm -> realm-0, keycloakServer -> https://keycloak.192.168.39.226.nip.io, password -> user-0-password),KO,List(),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$603/0x0000000840599840@1292737d,io.netty.channel.epoll.EpollEventLoop@4fa06f52)
=========================
HTTP request:
GET https://keycloak.192.168.39.226.nip.io/realms/realm-0/protocol/openid-connect/auth?login=true&response_type=code&client_id=client-0&state=3807ec13-145b-e0b9-2b73-91b8f6aa0349&redirect_uri=https%3A%2F%2Fkeycloak.192.168.39.226.nip.io%2Frealms%2Frealm-0%2Faccount%2F%23%2Fsecurity%2Fsigningin&scope=openid+profile
headers=
Accept: text/html,application/xhtml+xml,application/xml
Accept-Language: en-US,en;q=0.5
accept: application/json
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0
host: keycloak.192.168.39.226.nip.io
=========================
HTTP response:
status=
400 Bad Request
headers= 
Date: Tue, 16 Aug 2022 20:16:17 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 1729
Connection: keep-alive
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Robots-Tag: none
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
X-XSS-Protection: 1; mode=block
Content-Language: en

body=
<!DOCTYPE html>
<html class="login-pf">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

            <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title>Sign in to realm-0</title>
    <link rel="icon" href="/resources/qVNyD/login/keycloak/img/favicon.ico" />
            <link href="/resources/qVNyD/common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css" rel="stylesheet" />
            <link href="/resources/qVNyD/common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css" rel="stylesheet" />
            <link href="/resources/qVNyD/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css" rel="stylesheet" />
            <link href="/resources/qVNyD/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css" rel="stylesheet" />
            <link href="/resources/qVNyD/common/keycloak/lib/pficon/pficon.css" rel="stylesheet" />
            <link href="/resources/qVNyD/login/keycloak/css/login.css" rel="stylesheet" />
</head>

<body class="">
<div class="login-pf-page">
    <div id="kc-header" class="login-pf-page-header">
        <div id="kc-header-wrapper"
             class="">realm-0</div>
    </div>
    <div class="card-pf">
        <header class="login-pf-header">
                <h1 id="kc-page-title">        We are sorry...
</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">


        <div id="kc-error-message">
            <p class="instruction">Invalid parameter: redirect_uri</p>
        </div>



        </div>
      </div>

    </div>
  </div>
</body>
</html>

<<<<<<<<<<<<<<<<<<<<<<<<<

```

### How to Reproduce?

run the below command on the latest provision of Keycloak using the minikube:

```
./bin/kcb.sh --scenario=keycloak.scenario.authentication.LoginUserPassword \
--server-url=https://keycloak.{MASKED}.nip.io/ --users-per-sec=0.1 \
--log-http-on-failure
```

### Anything else?

I have attempted this workaround on https://github.com/keycloak/keycloak-benchmark/blob/main/benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala#L86 for the redirect_uri to match the new UI, however, it didn't resolve the issue.
```
var redirectUri = serverUrl.concat("/realms/").concat(realmName).concat("/account/#/security/signingin");
```

The failure is due to the https://github.com/keycloak/keycloak-benchmark/blob/main/benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala#L132 endpoint method, so would effect any and all the scenarios that consume this method.

**Comment by lhanusov** [comment]
@kami619 JFYI the redirect_uri is correctly set, but the problem is caused by the wrong client_id => client-0. Correct client_id is gatling.

**Comment by lhanusov** [comment]
The realm settings for the realm-0 must have enabled in the login section, part login screen customization the user registration.

**Comment by kami619** [comment]
> @kami619 JFYI the redirect_uri is correctly set, but the problem is caused by the wrong client_id => client-0. Correct client_id is gatling. Also the gatling client must have valid redirect uri set in the client access settings e.g. -> https://keycloak.192.168.39.229.nip.io/realms/realm-0/account/

Interesting, but we dont use the gatling client in this scenario.

**Comment by kami619** [comment]
> The realm settings for the realm-0 must have enabled in the login section, part login screen customization, the user registration.

Did it work for you with the changes in place ?

**Comment by lhanusov** [comment]
realm-0 created by the provisioning script is wrongly configured:
1. User registration must be enabled
2. Valid redirect uri set to *
3. Imported users like user-0/user-0-password
Currently 1 is disabled, 2 has some localhost value, 3 realm doesn't have any user

I speak about this step: https://github.com/keycloak/keycloak-benchmark/blob/main/provision/minikube/Taskfile.yaml#L266

**Comment by lhanusov** [comment]
To make it working - use the REST API dataset service - endpoints: 
1. delete realm-0: /realms/master/dataset/remove-realms?remove-all=true&realm-prefix=realm
2. create realm-0: /realms/master/dataset/create-realms?count=1
3. create clients in realm-0: /realms/master/dataset/create-clients?count=10&realm-name=realm-0
4. create users in realm-0: /realms/master/dataset/create-users?count=10&realm-name=realm-0

**Comment by kami619** [comment]
@lhanusov thanks, this needs to be implemented into the manage_gatling_client.sh, I will work on it. appreciate your work on finding this.

**Comment by lhanusov** [comment]
@kami619 Hi Kamesh, based on my further investigation of this bug and checking the script: manage_gatling_client.sh, I propose to remove this script and implement update to the DatasetProviderService class with an option to specify particular client name and assign client realm-management roles. To me it doesn't make sense to support both -> kcadm.sh cli and DatasetProviderService, also the REST API service is much faster in terms of large data.

**Comment by kami619** [comment]
@lhanusov I am in favor of doing that. cc: @ahus1 WDYT ?

**Comment by ahus1** [comment]
We still want people to use the benchmark Gatling Tests without the other parts, so it should be well documented (and probably even simple to use) without the dataset provider. So I see a use case for the shell script. I'll have to think about this a bit more later this week.

**Comment by kami619** [comment]
That is a fair point. I will schedule something next week to discuss this further, thanks @ahus1
