### ISSUE TITLE
Minikube provisioning - installation failures during container creating

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak-benchmark#160]
### Description

We need to add a documentation note: When using rebuild.sh script to install and provision the Keycloak environment in Minikube and user struggles with slow internet connection less then 2MB/s, it probably won't finish the deployment (container creating fails on dedicated timeout more then 15 minutes) and the script freezes in the infinite loop -> waiting for pods.
![Screenshot from 2022-08-18 20-49-54](https://user-images.githubusercontent.com/61745358/185595805-8c46f84b-65fe-4673-b8de-77eb30b5902d.png)
![Screenshot from 2022-08-18 20-50-17](https://user-images.githubusercontent.com/61745358/185595816-bd8761e0-1468-4f41-955e-f7ee122d4a4b.png)

**Comment by ahus1** [comment]
Thank for for reporting this. In the commit listed above, the installation guide has been update with the network speed as a pre-requisite and the error message you saw. This should be available on the project's web site once the GitHub action completes.
