### ISSUE TITLE
Minikube provisioning - Fedora linux go-task support

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak-benchmark#161]
### Description

The provisioning script rebuild.sh doesn't support the go-task binary: https://taskfile.dev/installation/#fedora.
It would be nice to add a condition to discover which binary to use (task or go-task): https://github.com/keycloak/keycloak-benchmark/blob/main/provision/minikube/rebuild.sh#L20, because the script will fail: "the command task is not found".

**Comment by ahus1** [comment]
Hi @lhanusov - the latest version of the project no longer calls `task` directly from the `rebuild.sh`, but leaves this to the user. I changed this to get the user run the `rebuild.sh` only once to setup minikube, and then run `task` on every change to the project. 

This way you're now able to run `go-task` instead. 

On the other hand, the recommended procedure is to download the binary and to put it into the `~/bin` folder like all the other tools. And the docs will refer to the `task` command in all places to indicate what command to run. I'll update the installation guide shortly with a hint.

**Comment by ahus1** [comment]
The new documentation pages:

* [Installing Keycloak on Minikube]( https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/installation)
  * [Installing task as a pre-requisite](https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/prerequisite/prerequisite-task)
