### ISSUE TITLE
Revise documentation for benchmark

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#187]
### Description

The make the benchmark module simpler to consume:

* revise the docs
* provide a nightly build

**Comment by ahus1** [comment]
@kami619 - I've updated the docs and made the latest snapshot release of the project more consumable by providing a snapshot release on the GitHub releases. It's beging built after a change on the main branch. 

I also updated the scenario to no longer require a registration link on the login page in the standard Login/AuthorizationCode scenario, as that was only needed in another, currently inactive scenario. 

To avoid conflicts with other PRs and to provide this link to internal users I chose to merge it right away. If you have the time, I'd be happy if you could review the commit and let me know what's missing.

**Comment by kami619** [comment]
sure thing, I will find some time to review this, thanks  @ahus1  for the nightly release process 👍🏼
