### ISSUE TITLE
Allow accepting self-signed certs

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-benchmark#191]
### Description

Allow the use of self-signed SSL certs when testing a Keycloak instance. 

### Motivation

Currently, scenarios fail
```
> j.n.s.SSLHandshakeException: error:10000438:SSL routines:OPENS     12 (100.0%)
SL_internal:TLSV1_ALERT_INTERNAL_ERROR
```

**Comment by ahus1** [comment]
@xgp - Are running `kcb.sh` which is then calling Gatling, or are you running `manage_gatling_client.sh` to prepare the Keycloak instance?

Could you please provide the CLI you used? Thanks!

**Comment by xgp** [comment]
In this instance, I used the manual setup steps from the guide, and then used `kcb.sh` to run the Gatling benchmark:
```
./kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode \
  --server-url=https://localhost \
  --realm-name=realm-0 \
  --username=user-0 \
  --password=user-password-0 \
  --client-id=gatling \
  --client-secret=<removed> \
  --client-redirect-uri=http://localhost:8081 \
  --log-http-on-failure
```

My Keycloak is running locally behind a Caddy reverse proxy. I wanted to do this in order to model a production setup more closely. Caddy is set up to create a self-signed cert like this:
```
caddy reverse-proxy --from https://localhost:443 --to http://keycloak:8080
```

**Comment by ahus1** [comment]
Thanks for sharing the details. We use self-signed certificates when running performance tests against the minikube setup without additional options and without problems.

I'll need to try `caddy` to see what's different there. I'll have a look once I finish some tasks for storage migration in the keycloak repository.

**Comment by ahus1** [comment]
I had a look and found the following: 

* When running caddy as a reverse proxy, caddy expects the client to send a server name indicator (SNI). Without that, it will drop the connection. You can try this as follows:
  * ` openssl s_client -connect localhost:443` will connect and then immediately drop the connection as no SNI is sent
  * ` openssl s_client -connect localhost:8443 -servername localhost` will connect as expected, as the SNI matches the hostname on the caddy command line
* When using Java, it will send the SNI only when the hostname contains a dot, see https://gamlor.info/posts-output/2019-09-05-java-client-sni/en/ ... I also saw that when debugging TLS on the Java client side

So I assume this will work once you have a real hostname. At the same time once you choose a real hostname with caddy. In my local setup this failed as it wasn't able to retrieve a certificate for that (which is expected). 

While this explains the behavior, it doesn't lead to a straight answer ... except maybe: when using Gatling and Java, don't use caddy as a reverse proxy on localhost.

**Comment by xgp** [comment]
@ahus1 Thanks for looking into that. Great detail.

**Comment by ahus1** [comment]
Reading this issue, I assume that this questions has been answered. Having a load balancer like caddy in our setup and connecting to it using "localhost" is not a standard scenario in the setups described here, still I chose to add it to the docs: https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/error-messages
