### ISSUE TITLE
Documentation: What scenarios require seed data

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-benchmark#192]
### Description

It's not clear from the documentation when seed data is necessary, only
> Depending on the kind of tests to run, this might be optional and can be skipped.

from https://www.keycloak.org/keycloak-benchmark/getting-started

### Details

Maybe put the dataset required in each of the scenario descriptions. For example, in this scenario https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario/authorization-code it's not clear if a seed dataset is necessary, or if it creates users with the given service account.

**Comment by ahus1** [comment]
@xgp - I agree the documentation is lacking information, and the pre-requisites for each scenario should be started clearly. 

If we would add the dataset provider as a pre-requisite, it would make it difficult for people to run these tests with a different setup, so I think documenting the requirements is the way to go. 

The only scenario that I started this for is is the `AuthorizationCode` scenario. I'd like to fix this one first, and then model all other scenarios after this template. 

Today [the page of the scenario](https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario/authorization-code) lists the following requirements: 

> Realm, user and client exist with the values listed on the CLI.

The page contains also a CLI as follows: 

> bin/kcb.sh \
  --scenario=keycloak.scenario.authentication.AuthorizationCode \
  --server-url=http://localhost:8080/ \
  --realm-name=realm-0 \
  --username=user-0 \
  --password=user-password-0 \
  --client-id=gatling \
  --client-secret=setup-for-benchmark \
  --client-redirect-uri=http://localhost:8081 \
  --log-http-on-failure

I'll check this procedure locally and will then report back to you.

**Comment by xgp** [comment]
@ahus1 Thanks for looking at this. I am looking at this with ignorant eyes, and so I am trying to document my difficulty in understanding how to use the tools.

It would be good to note if it is possible to use some of the other variables with the `AuthorizationCode` scenario (or any scenario). E.g. can these values be used?
```
  --realms=10 \
  --users-per-realm=100 \
```
Or at least document on the [Configuring Keycloak Benchmark](https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/configuration) page which values in the [Config.java](https://github.com/keycloak/keycloak-benchmark/blob/main/benchmark/src/main/java/org/keycloak/benchmark/Config.java) code can be used with which scenario, and how it effects the behavior of that scenario.

My specific used case is that I would like to run the `AuthorizationCode` scenario for multiple realms/users to simulate heavy concurrent use of a single Keycloak instance/cluster. I assumed that I needed to run the dataset module to create 10x100 realms x users, and then run the benchmark `AuthorizationCode` scenario with the above variables. However, after trying that, it appears that is not possible with the existing scenario. A little more documentation would have saved me some headache. ;)

**Comment by ahus1** [comment]
@xgp - I tested it locally and found a bug in the docs. Instead of `--password` it should have been `--user-password`. I just pushed a change together with some more clarifications: b3569db7755ed2425ae22e1c2ae878ad92d85f36

This should enable you to run the test with a single user: https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario/authorization-code

The scenario can be also be run with multiple users and on multiple realms, assuming that each entity has the same prefix ("realm-" and "user-" "), and start their numbering with "-0". I plan to update the [Configuring Keycloak Benchmark](https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/configuration) with more details later today.
This is a common feature to all scenarios, so I'll describe it there in more general way.

**Comment by ahus1** [comment]
@xgp - please stand by for the next update of the docs that will contain more details on this.

Sneak peak: If you plan to use the dataset module, the dataset module would set up Clients starting with `client-0`, and one would use those for the test run.

**Comment by ahus1** [comment]
The [configuration guide](https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/configuration) now includes a list of most options that can be specified on the CLI. 

It also details now setups of multiple keycloak / realms / users / clients work. Some properties (mostly those that are scenario specific) are still missing.

I hope that unblocks your current effort, and answers the original question. 

Please let me know what is missing, or if this issue can be closed. We'd then open an issue to document the remaining parameters and scenarios.

**Comment by xgp** [comment]
This unblocks what I was working on. Thank you!

**Comment by ahus1** [comment]
Created two follow-up issues: #194, #195
