### ISSUE TITLE
For DB usage, add a metric about IOPS used

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#197]
### Description

When running on cloud providers, IOPS need to be tracked and measured. For that, it would be good to monitoring writes and reads. 

The closes thing that the current setup offers would be the `container_fs_writes_total` and `container_fs_reads_total` metrics published by cadvisor for each container. 

With cadvisor having some gaps now and then, it might be safe to calculate the `rate()` or a range of 2-5 minutes (depending on how the tests go).

### Motivation

Gather a metrics that could relate to IOPS.

**Comment by ahus1** [comment]
@kami619 - I'd be happy to hear your thoughts on this. Do you want to pick up this task?

**Comment by kami619** [comment]
@ahus1 sure thing, I can look into this task
