### ISSUE TITLE
initialize-benchmark-entities.sh should be packaged in the ZIP file

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#201]
### Description

The distribution ZIP file contains at the moment only `bin/kcb.sh`, and not `initialize-benchmark-entities.sh`. 

It might be beneficial to the users to have that script part of the distribution. For that, the file would need to be moved to `src/main/content/bin`. 

The same might be true for `generate-custom-report.sh`. 

@kami619 - I'd be happy to hear your thoughts on this.

### Motivation

A users should have everything at hand after downloading the ZIP or tar file.

**Comment by kami619** [comment]
oh yeah, I think that makes sense. @ahus1 I just saw this, should I make this change part of the #200 ?

**Comment by ahus1** [comment]
I don't think so, let's make it another PR as #200 has now been reviewed and is ready to be merged.

**Comment by kami619** [comment]
Ok, I can work on this then. Thanks.
