### ISSUE TITLE
Run minikube on an Intel Mac and report any gaps

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#210]
### Description

Run minikube on an Intel Mac and report any gaps from the point of view of

 - Install minikube provisioning on Mac from scratch
 - Run the load tests and make sure they work with all the Observability tooling on the Mac OS

### Motivation

This task would help motivate more people from the community to pick up this provisioning and help keep Keycloak performant

**Comment by nehachopra27** [comment]
As part of this PR, installed Keycloak on minikube with the guide and reported any discrepancies. Also tried to follow the approach in kubernetes and benchmark guide to see if I am able to follow them without any prior knowledge.
