### ISSUE TITLE
Do not force user registration enabled when running tests that don't require user registration

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak-benchmark#23]
### Environment

Version: 0.4

### Description
Currently, when you try to run `keycloak.scenario.authentication.AuthorizationCode` requests fail due to an error when parsing the login page to fetch the registration form link.

```
---- Errors --------------------------------------------------------------------
> regex(href="/auth(/realms/[^"]*/login-actions/registration[^"]     32 (100.0%)
*)").find.transform.exists, found nothing
```

The registration link should be mandatory when running scenarios that don't require user registration.

### Workaround

Enable the `User Registration` setting to realms.

**Comment by ahus1** [comment]
As part of a commit cc227b4cc907c712e9ade856b72d5c522c09060c there are now two methods: openLoginPage() and openLoginPageWithRegistrationLink(). This allows tests to choose if they really need user registration.
