### ISSUE TITLE
Tune the log level of "Handling transient entity in delete processing" WARN with JPA Map + Postgres + AuthorizationCode scenario

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#243]
### Describe the bug

We seem to be logging this info excessively, close to 34000 times during a OIDC login scenario for the below benchmark parameters,

This would be better to be tuned to be at the proper log level.

Storage : JPA Map
Database : PostgreSQL DB
Scenario : AuthorizationCode

max concurrent login request per sec : 16 reqs/sec
duration of the load simulation : 3000 secs

Sample of log:
{"timestamp":"2022-10-22T12:50:27.462Z","sequence":19705,"loggerClassName":"org.hibernate.internal.CoreMessageLogger_$logger","loggerName":"org.hibernate.event.internal.DefaultDeleteEventListener","level":"INFO","message":"HHH000114: Handling transient entity in delete processing","threadName":"executor-thread-1020","threadId":1053,"mdc":{},"ndc":"","hostName":"keycloak-1","processName":"QuarkusEntryPoint","processId":1}

![image](https://user-images.githubusercontent.com/3415105/199615359-4e63dc95-5fad-4ca6-88be-847322cbc69c.png)

### Version

keycloak nightly image 11/2/2022

### Expected behavior

This log shouldn't be logged at INFO level, which could clog any logging platforms and causing issues downstream

### Actual behavior

The logs are logged excessively at INFO level with the aforementioned scenario and storage layer conditions

### How to Reproduce?

Once you provision the minikube based keycloak setup with the below storage configurations, run the below simulation

`task reset-keycloak KC_STORAGE=jpa KC_DATABASE=postgres`

```
./bin/kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=https://keycloak.IP/ --concurrent-users=16 --realm-name=test-realm --logout-percentage=100 --measurement=3000 --user-think-time=3
```

**Comment by ahus1** [comment]
Created an upstream issue to discuss different options: https://github.com/keycloak/keycloak/issues/15310

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
