### ISSUE TITLE
Add Grafana Phlare to the monitoring stack inside the provision/minikube

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#258]
### Description

To enable continuous profiling in minikube based provisioning, add Grafana Phlare to the existing monitoring stack

### Motivation

This tooling will enable us to review various performance metrics for a specific pod within a namespace in a seamless fashion. Right now, we can achieve this by using Cryostat's Java Flight Recording, but that is only limited to JVMs and not all applications involved, or using tools like [kubectl-flame](https://github.com/yahoo/kubectl-flame) which needs an additional package manager to install it.

### Details

https://grafana.com/docs/phlare/latest/operators-guide/deploy-kubernetes/

We can use this installation guide to deploy the helm chart into the existing minikube provisioning.

Noteworthy:

- This is a very young project, the first release happened just two weeks
- We have to figure out, if this would exasperate the scrape timeout on the prometheus front or similar issues, if run for longer durations

**Comment by ahus1** [comment]
Thanks for bringing this up. I had a short look at it: 

* It seems to depend on a special build of Grafana, and the customizations point to a special repository. The current 9.2.x release doesn't know about he phlare datasource type. I assume it will be part of the Grafana 9.3 release.
* At the moment, Java applications need to be modified to expose their metrics for phlare. There is currently no Java agent available that would allow us a Java application without a modification. I opened an issue here https://github.com/grafana/JPProf/issues/20 and I hope this will be possible in the future. 

I could still prepare a branch to try out things.

**Comment by kami619** [comment]
@ahus1 thanks for such a blazing fast review of this task 🚀  I dont think it is blocking any of my tasks, but it would be great to understand the amount of work needed, at your convenience.
