### ISSUE TITLE
Add new smoke tests to run short load simulations on GHA wofklow to verify benchmark compatibility with latest keycloak nightly

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#269]
### Description

Add new smoke tests to run short load simulations on GHA wofklow to verify benchmark compatibility with latest keycloak nightly

### Details

Create a new github workflow to run when there are changes within the benchmark module as well as with a defined frequency to verify the compatibility of the Keycloak nightly images

**Comment by ahus1** [comment]
It would be good to have those, still we managed to go without for about a year. Closing this to keep the backlog managable.
