### ISSUE TITLE
Cryostat integration using helm chart

### ISSUE THREAD

**Issue by andrewazores** [keycloak/keycloak-benchmark#293]
### Description

Cryostat publishes an upstream helm chart:

https://github.com/cryostatio/cryostat-helm

Rather than carrying custom k8s resources that replicate the functionality of setting up a Cryostat instance for benchmarking, it may be worthwhile to just use the helm chart.

### Motivation

Presumably this will be easier for this project's maintainers to carry since any required configuration changes for future Cryostat release versions should also be reflected in the helm chart, so this would make Cryostat upgrades simpler.

**Comment by ahus1** [comment]
When running in OpenShift, we're using the Crypostat Operator, eventually we might do the same in Minikube. As this issue has been open for a while and not implemented due to other priorities and this is not urgent as of now, I'm closing it to tidy up our backlog.
