### ISSUE TITLE
Keycloak benchmark documentation should mention the kvm2 setup

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak-benchmark#300]
### Description

When running the `rebuild.sh` script as described in step 3 of the [documentation](https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/installation), I've run into a pop-up window requesting authentication and saying that `System policy prevents management of local virtualized systems`. After entering the password, the command was left blinking indefinitely, and no progress was ever made.

It turns out that in my local machine I had never set up `kvm2` properly (https://minikube.sigs.k8s.io/docs/drivers/kvm2/), and my user had to be added to the `libvirt` group. A simple command `sudo usermod -aG libvirt $USER` was enough to fix the group membership and allow the `rebuild.sh` script to finish.

Thus I'm requesting that the documentation is updated with a small section on to verify the `kvm2` setup before running the script.

Also, when running the `task` command in step 4, it first failed with `task: Failed to run task "tlsdisableagent": exit status 1`, which turns out to happen because of a missing `JAVA_HOME` env variable. It is probably a good idea to mention the JAVA_HOME requirement in the docs as well.

**Comment by kami619** [comment]
@sguilhen thanks for raising this, both valid comments. @ahus1 do you think adding the details around these in the https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/error-messages docs would be a good place or should I add it directly under the relevant installation docs for both 

1. kvm privilege issue
2. missing java_home requirement

**Comment by ahus1** [comment]
@kami619 - IMHO we should put users on the right path before they get the error message. Therefore I'd recommend to update the docs: 

* https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/prerequisite/prerequisite-minikube could be enhanced with a Linux section explaining that KVM2 is necessary, how to set it up in a nutshell, link to the minikube page above, and a one-line shell command to verify that is has been setup correctly.
* Java is not yet listed here https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/installation ... so it should be added, with a page of the usual structure, plus a one-liner to test that it is set up. 

Once that is complete, and we think people will still face this situation, consider the following: 
* Add a check `rebuild.sh` that shows a good error message is the prerequisites on Linux about kvm2 are not met
* Add a task to the taskfile before running Maven to see if Java is set up correctly and show a descriptive error message. 

Let me know if you have the time for this, and if you want to split this task. Whatever you choose, I'd be happy to review things.

**Comment by kami619** [comment]
@ahus1 ok, I will take this up, thank you for the suggestion and I think it is better to make the user to not go through the user in general, I shall look into creating a PR for this.
