### ISSUE TITLE
Why does using Keycloak admin-rest-api directly is slow? 

### ISSUE THREAD

**Issue by tamirMoshiashvili** [keycloak/keycloak-benchmark#31]
Hi,
I tried Keycloak recently and also experimented with its admin-rest-api.

I noticed that there are some rest-requests that take a lot of time to return a response to the user, although I can see the effect of the request in the console instantly.
For example - deleting group. 

After searching for reasons to that behavior, I could not find any sources besides the **Warning** in your readme that tells that using the admin-rest-api directly is slow in some environments, under the *Setup* section.

Can you explain why did you mention that it is slow? (although I can see the change in the console right away)
And if there is something that I can do (as configuration) to improve performance regarding the admin-rest-api?

**Comment by mposolda** [comment]
@tamirMoshiashvili It is slow due the fact that there is bigger amount of REST requests to create objects. For example to create 1000 users you need 1000 separate REST requests when you use admin REST API. Each REST request introduces some overhead (EG. runs in it's own transaction, HTTP request processing, lookup of the realm and some other objects, which need to be done separately for each request etc).

With the usage of "Dataset" tool in this project, you can create 1000 users with 1 request and that is what makes it more effective.

**Comment by mposolda** [comment]
@tamirMoshiashvili Closing this. Feel free to re-open if you still have any issues.

**Comment by tamirMoshiashvili** [comment]
@mposolda thanks for your reply, it did help but not fully answered my questions.
I did not use *keycloak-benchmark* at all, but the docs here are the only place stating *keycloak admin rest api* is slower and should be avoided. 
I ask about **single request**. 

The main problem is time-difference between performing an action with *keycloak admin console* and *keycloak admin rest api*.
- delete group in console - few seconds
- delete group by rest-requests takes about 40 seconds


Does your explanation about a request can be that signifacnt? 
> Each REST request introduces some overhead (EG. runs in it's own transaction, HTTP request processing, lookup of the realm and some other objects, which need to be done separately for each request etc).

**Comment by mposolda** [comment]
> @mposolda thanks for your reply, it did help but not fully answered my questions.
I did not use keycloak-benchmark at all, but the docs here are the only place stating keycloak admin rest api is slower and should be avoided.
I ask about single request.

Ah, Ok, this forum is related to keycloak-benchmark. Please use keycloak-user forum for questions related to keycloak admin REST API in general.

> The main problem is time-difference between performing an action with keycloak admin console and keycloak admin rest api.

>    delete group in console - few seconds
>    delete group by rest-requests takes about 40 seconds

> Does your explanation about a request can be that signifacnt?

The admin console uses admin REST API by default. The request for delete group from console is also uses admin REST API under the covers. The times you have indicate that you're calling admin REST API in some strange / invalid way. I suggest to use some browser plugin (EG. Web developer in chrome) to check what REST requests are called by console under the covers.
