### ISSUE TITLE
Add support to openshift provisioning module to create base entities to support gatling benchmark and dataset scripts

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#314]
### Description

Add support to openshift provisioning module to create base entities to support gatling benchmark and dataset scripts

- Similar to minikube module we need to have support to create the needed service account enabled client, test-realm and users to start a benchmark against the Openshift cluster based Keycloak instance.
- Akin to the above point, we also need to be able to deploy dataset module to the Openshift cluster based Keycloak instance and create needed datasets for various entities.

### Details

The question I have for this particular feature request is along the lines of implementation for gatlinguser task from minikube/Taskfile.yaml

Do we want to create these `tasks` under the `common/Taskfile.yml` ? That way we can simply modify the `gatlinguser` to pick up the `KC_HOSTNAME_SUFFIX` from the `.env` file to be under a conditional if block to only run the varied version of the below bash command when the `KC_HOSTNAME_SUFFIX` variable exists in the context.

Suggested Change:

```
- >
  bash -c '
  if [ "{{.KC_HOSTNAME_SUFFIX}}" != "" ]; 
    then ../keycloak-cli/keycloak/bin/kcadm.sh config credentials --server https://keycloak.{{.KC_HOSTNAME_SUFFIX}}/ --realm master --user admin --password admin;
    else ../keycloak-cli/keycloak/bin/kcadm.sh config credentials --server https://keycloak.{{.IP}}.nip.io/ --realm master --user admin --password admin;
  fi'
```

For the dataset module, I believe there would be no changes needed, but would need some testing to make sure we don't hit any runtime issues.

**Comment by ahus1** [comment]
+1 for moving over the dataset tasks to the common taskfile. 

I suppose we might need the Keycloak URL in several places soon, so you might want to add an environment variable that carries the whole URL of Keycloak to avoid duplicating the logic in several places. If this involves too much refactoring, feel free to push forward the refactoring.
