### ISSUE TITLE
`generate-custom-report.sh` fails due to nuxeo nexus issues

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak-benchmark#329]
### Describe the bug

The following jar download doesn't work:
https://github.com/keycloak/keycloak-benchmark/blob/09895632c338efa2943f7dddccd2e104f0ba456c/benchmark/src/main/content/bin/generate-custom-report.sh#L19

because Nuxeo Nexus seems to have some issues or the artifact is unavailable.

By default, it uses version 6.0
https://maven-eu.nuxeo.org/nexus/service/local/repositories/vendor-releases/content/org/nuxeo/tools/gatling-report/6.0/gatling-report-6.0-capsule-fat.jar

I also searched other versions from https://mvnrepository.com/artifact/org.nuxeo.tools/gatling-report and haven't found any working jar.

### Version

0.10-SNAPSHOT

**Comment by kami619** [comment]
I reviewed this problem and able to reproduce this locally, one of the options discussed with @ahus1 was to host the working jar from an older version in our own release binaries and consume it directly in our script. I will work on a PR for this soon. thanks for reporting this @mhajas
