### ISSUE TITLE
NonLocalReturnControl

### ISSUE THREAD

**Issue by lwalukie** [keycloak/keycloak-benchmark#337]
### Describe the bug

When attempt to trigger keycloak tests like below:

`./kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=<url_to_my_keycloak> --realms=10 --users-per-realm=200 --users-per-sec=30 --measurement=30`

I can observe errors like: **s.r. NonLocalReturnControl** (like on attachment)
![Zrzut ekranu 2023-05-19 o 15 07 56](https://github.com/keycloak/keycloak-benchmark/assets/2714587/b5206327-4b6e-4180-b0cc-d31582ad4c3f)
Seems like this error has nothing to do with keycloak, but this is some Scala specific issue.
Could you please check it?

### Version

21.1.1

**Comment by kami619** [comment]
@lwalukie thanks for reporting the issue, we shall try to reproduce this issue and get back with some more info. thank you.

**Comment by lwalukie** [comment]
One hint from my side - it turned out that reason for that was infinite redirection loop, which was caused by incorrectly configured keycloak cluster (pods did not find themeselves). Nevertheless I think keycloak benchmark should handle such cases a bit more clearer to better indicate what the issue is.

**Comment by lwalukie** [comment]
Sure, you can setup kubernetes cluster with keycloak and do not set correct dns ping parameters. The thing is that root cause for this is that there are multiple instances of keycloak within the same kubernates cluster which do not see each other.

**Comment by ahus1** [comment]
Closing this issue as there hasn't been progress for ~6 months.
