### ISSUE TITLE
Add basic single pod failure scenario

### ISSUE THREAD

**Issue by PavelVlha** [keycloak/keycloak-benchmark#363]
Add to https://github.com/keycloak/keycloak-benchmark/blob/main/.github/workflows/rosa-run-benchmark.yml a simple scenario that kills a keycloak pod randomly and verifies there are no errors

**Comment by kami619** [comment]
the basic pod delete script is ready, now have to implement this in a workflow to simulate the failures and measure them.

```
#!/bin/bash
# Randomly delete pods in a Kubernetes namespace.
set -e

: ${DELAY:=30}
: ${NAMESPACE:="aaa-keycloak"}
while true; do
  kubectl \
    --namespace "${NAMESPACE}" \
    -o 'jsonpath={.items[*].metadata.name}' \
    get pods -l app=keycloak | \
      tr " " "\n" | \
      shuf | \
      head -n 1 |
      xargs -t --no-run-if-empty \
        kubectl --namespace "${NAMESPACE}" delete pod
  sleep "${DELAY}"
done

```

inspired from https://github.com/jnewland/kubernetes-pod-chaos-monkey/blob/master/chaos.sh

**Comment by mhajas** [comment]
If I understand correctly `kubectl delete pod` will kill the pod gracefully, which means it can participate in cache rebalancing. Which is something we probably want to avoid. Should we add `--grace-period=0 --force` to the command?

WDYT @pruivo ?

**Comment by ahus1** [comment]
@pruivo / @mhajas - the `--force` option behaves a little different than expected: It will remove the resources from the API server, even if the Pod is still running. 

Therefore I think the closest we could get to this is use `--grace-period=1` which is documented as "immediate" shutdown when looking at the docs of `kubectl delete pod --help` 

BTW: "verifies there are no errors" -> this strategy will show errors, as requests currently running will return failures. Let's still implement it and see how many fail.

**Comment by kami619** [comment]
good point @ahus1 I will use `--grace-period=1` as the option for this version of the failure flow. I agree, the intent would be to report back with the `error` details at the end of the run.

**Comment by pruivo** [comment]
does anyone know if `kill -9 <java pid>` would work too? 

Errors are expected in this scenario (Infinispan will throw mostly `TimeoutException`) because JGroups takes a while to detect failures and do the rebalance.

**Comment by ahus1** [comment]
Good idea, this will work as well. And we already know the PID as it will always be `1`. So we could use a `kubectl exec` here.

**Comment by mhajas** [comment]
I like the idea with `kill -9 <pid>` sounds like it is the closest to a real failure we can get.

**Comment by ahus1** [comment]
After some pair-googling on the topic, a PID 1 can't be killed with `-9`: https://unix.stackexchange.com/questions/457649/unable-to-kill-process-with-pid-1-in-docker-container.

As that is the case, the `kubectl delete pod` delivers the same results, and would be simpler to use.
