### ISSUE TITLE
Add SLO metrics for Client Credential Grant and Authorization Code to Keycloak

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#372]
Building blocks of the solution:
* Identify the different endpoints in Keycloak that should collect metrics for the two scenarios.
* Collect duration metrics via Micrometer as histograms, so they can be aggregated across a cluster. 
* Collect request counts via Micrometer as histograms, so they can be aggregated across a cluster. 
* Provide a PromQL query / minimal Grafana dashboard which collects the SLO for each scenario. 

**SLO candidates:**

Client credential grant
* 99% of requests serviced in < 50 ms
* 99.99% of requests are successfully completed

Authorization code flow
* 99% of requests serviced in < 200 ms
* 99.99% of requests are successfully completed

**Design discussion:** 

Automatically added metrics for URL endpoints didn't work well with subresources, see https://github.com/keycloak/keycloak/issues/17281. An issue to support this with Quarkus is still open, see https://github.com/quarkusio/quarkus/issues/31497. It might still be worth checking the current state of things as Keycloak has been upgrades to Quarkus 3.1.x. This might or might relate to https://github.com/keycloak/keycloak/issues/9036

While subresource metrics don't work well with Quarkus' out-of-the-box support, they work nicely with the OTEL agent. 

_Summary:_ The simplest way seems to be to add the metrics would be to use the OTEL agent and gather the metrics on a per-URL base with a duration and a HTTP status code. If this doesn't work as expected, we'll consider other options.

**Next steps/out of scope here:** 

* For a test, run a query directly against Prometheus to see if the SLO have been met during the test's duration.
* Evaluate if elastic loadbalancer and haproxy get meaningful metrics

**Comment by ahus1** [comment]
Evaluate if elastic loadbalancer and haproxy get meaningful metrics

**Comment by mhajas** [comment]
The following was delivered as part of this issue:
- OTEL now works with Openshift
- A new dashboard was introduced with SLO data for Client credentials grant
- Jaeger now works with Openshift

SLO dashboard for Authorization code flow was not added, but we decided to close this now and reopen it or create a new issue for the rest of the work when needed.
