### ISSUE TITLE
Run proper failure tests using already prepared script

### ISSUE THREAD

**Issue by PavelVlha** [keycloak/keycloak-benchmark#381]
- Understand and describe one scenario where KC fails without recovery.
- Find a scenario where a new Pod of Keycloak doesn't become ready after 120 seconds

**Comment by kami619** [comment]
We ran failure test scenarios and here is the below summary of the tests:

- AuthorizationCode with 80 users-per-sec was able to reach a maximum throughput of 75 reqs/sec(for a single endpoint) with less than 300 ms response time for all endpoints and 0 failures
- AuthorizationCode with 70 users-per-sec with simulated failure of pods, we were able to get 63 reqs/sec(for a single endpoint) with more than 12 seconds response time and about 13% errors, breaking both SLA's we had in mind for this scenario.

Observations:
- We found the cache entries are going into only 1 pod, even when the sticky sessions were disabled, we wanted to confirm this in our subsequent runs - #393 
- We also wanted to define the desirable capacity, given we were only able to get to 75 reqs/sec with a 80 users-per-sec user load for a 3 pod Keycloak setup - #394
