### ISSUE TITLE
Define desirable capacity for single cluster

### ISSUE THREAD

**Issue by PavelVlha** [keycloak/keycloak-benchmark#394]
For a "medium" sized single cluster setup, we want to see the following numbers:

* **280 users logins per second**
This assumes 100_000 user logging in during the first hour of the day, with a peak factor of 10 to allow for spikes in the user load.

* **1000 client credential grants per second**
This is a substitute measure for having 100_000 active sessions, where the access token is refreshed every 240 seconds (300 seconds access token valid time with 60 seconds in advanced), assuming that 50% of the users are active and refreshing their tokens this way. The other 50% are idle, and will not refresh their tokens. There is also a peak factor of 5 in this calculation to allow for peaks

These new load elements will be part of #393, and will be reviewed afterwards

New suggested Gatling scenario instead of the substitute one to see if refresh tokens really scale as needed. The steps or the new scenario are:
1. Login 100_000 users as fast as possible
2. Refresh access token when 60 seconds are left for the access token

**Comment by ahus1** [comment]
Follow-up issue #416 created for the new Gatling scenario. Closing.
