### ISSUE TITLE
Infinispan state transfer never completes

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak-benchmark#396]
If a node joins the cluster during a state transfer, it may happen that the state transfer never ends which makes it impossible for the joiner to join the cluster.

See https://issues.redhat.com/browse/ISPN-14982 for more details.

**Comment by ahus1** [comment]
This corresponds with the following issue in the Keycloak project: https://github.com/keycloak/keycloak/issues/21256

**Comment by ahus1** [comment]
Included in 14.0.12
