### ISSUE TITLE
Startup with OTEL enabled is too slow

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak-benchmark#401]
Restarting a pod with OTEL takes 60 seconds, but 24 seconds without it.

**Comment by mhajas** [comment]
@ahus1 I tested your suggestion: https://github.com/mhajas/keycloak-benchmark/commit/31d4ebbcf5c9bf5e49133c0db798fddffd24a8e8

But I see no reasonable improvement in startup time after moving the otel agent to `emptyDir`.

**Comment by mhajas** [comment]
Also, a few more observations. The following numbers are observed at the daily cluster with `m5.xlarge` machines.

| | Total restart time | Keycloak reported startup time |
| --- | --- | --- |
| With otel | ~63s | ~22s |
| Without otel | ~24s | ~8s |

**Comment by ahus1** [comment]
It seems there is nothing we can do about this as of today.
