### ISSUE TITLE
rearrange the pieces of kc-chao.sh, kcb.sh and distributed load testing playbooks for better execution path

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#405]
we received some good [feedback](https://github.com/keycloak/keycloak-benchmark/pull/402#discussion_r1246757042) as part of the #393.

So as part of the next steps, we would like go back to drawing board for a bit and think from the bigger picture to rearrange some of the pieces of code thats currently part of kcb.sh and kc-chaos.sh to better suit execution path of single node vs distributed node load tests and k8s vs non-k8s tests.

**Comment by ahus1** [comment]
Closing for now. Will return to improvements once we do more failure testing / it hurts us more
