### ISSUE TITLE
Reduce OTEL warnings on startup

### ISSUE THREAD

**Issue by PavelVlha** [keycloak/keycloak-benchmark#407]
Upstream issue created: https://issues.redhat.com/browse/ISPN-14997

PR created: https://github.com/infinispan/infinispan/pull/11064

**Comment by ahus1** [comment]
PR merged to upstream. Downstream PR created: https://github.com/infinispan/infinispan/pull/11086

**Comment by ahus1** [comment]
14.0.12 was released.
