### ISSUE TITLE
Update scalability scenarios to use EC2 Gatling load runners

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#419]
The current runners use GitHub Actions only which don't provide results due to long latencies, and not being able to create enough connections per second. 

This way the current setup doesn't provide the numbers and regression testing results we want to see. 

Therefore the GHAs should use Gatling with EC2 instances as runners

**Comment by kami619** [comment]
this feature is now part of the GHA workflow - https://github.com/keycloak/keycloak-benchmark/blob/main/.github/workflows/rosa-scaling-benchmark.yml#L138
