### ISSUE TITLE
Add batch transactions to group creation

### ISSUE THREAD

**Issue by artur-baltabayev** [keycloak/keycloak-benchmark#42]
### Description

To avoid timeouts when creating large amounts of groups it would be helpful to process them in batches.

### Details

PR : https://github.com/keycloak/keycloak-benchmark/pull/41

**Comment by ahus1** [comment]
@artur-baltabayev / @pedroigor - there has been a PR for this issue, still this issue is open. I wonder if this issue can be closed. Thanks!
