### ISSUE TITLE
A new commit to result-data branch is not triggering a new aggregate-results workflow in GH Actions

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#421]
### Describe the bug

Commit in question : https://github.com/keycloak/keycloak-benchmark/commit/47086cfc16d0b5e61ba5593cdfbf1d2b18df75fd

We expect the new commits to `result-data` branch to trigger a new run for the https://github.com/keycloak/keycloak-benchmark/blob/result-data/.github/workflows/aggregate-results.yaml#L6 aggregate-results github workflow

### Version

NA

### Expected behavior

I would expect a workflow run to happen for https://github.com/keycloak/keycloak-benchmark/blob/result-data/.github/workflows/aggregate-results.yaml and generate a static website with aggregated benchmark results

### Actual behavior

dont see that happening

### How to Reproduce?

run a scalability benchmark and make sure the results.json is committed to the `result-data` branch of keycloak-benchmark

**Comment by ahus1** [comment]
I found that push notifications don't work when the push comes from a GitHub action, see https://github.com/orgs/community/discussions/37103

Will use `gh` for this instead.
