### ISSUE TITLE
isup.sh script declares an early success before all the pods are fully restarted in a `task keycloak`

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#422]
### Describe the bug

isup.sh script declares an early success before all the pods are fully restarted in a `task keycloak`

### Version

keycloak-benchmark latest main

### Expected behavior

We would want the isup.sh script to wait for all pods restarts to complete before it declares success.

### How to Reproduce?

run `task -f keycloak` against an existing openshift deployment and watch for when the pods are restarted

### Anything else?

Skip to 00:39 of the video to see the issue at play.

https://github.com/keycloak/keycloak-benchmark/assets/3415105/42b5c00d-47a1-4a62-853f-ceb815af8288

**Comment by ahus1** [comment]
Updated `isup.sh` to also wait for rolling updates to complete.
