### ISSUE TITLE
Aurora multiple regions failover scenario

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#445]
Investigate how a cross-DC failover for a Aurora database works. 

Possibly summarize the finding in a single slide and present it to the team. Investigate on how this can be scripted for an automated test.

**Comment by ahus1** [comment]
Postponed for a later sprint.

**Comment by ryanemerson** [comment]
[Aurora Global DB deployments](https://catalog.us-east-1.prod.workshops.aws/workshops/098605dc-8eee-4e84-85e9-c5c6c9e43de2/en-US/lab9-aurora-global-db)

[Aurora Failover](https://aws.amazon.com/blogs/database/deploy-multi-region-amazon-aurora-applications-with-a-failover-blueprint/)

**Comment by ahus1** [comment]
Interesting read on Aurora High Availability in a single-DC-but-multiple-AZ setup, and Aurora global database and the concepts of "switchover" (manually planned) and "failover" (unplanned outage of primary) with their different "recovery time objectives" (RTO) and "recovery point objective" (RPO).

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.AuroraHighAvailability.html / https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-disaster-recovery.html

**Comment by ryanemerson** [comment]
https://github.com/aws-samples/amazon-aurora-global-database-endpoint-automation

**Comment by mhajas** [comment]
jFTR I tested failover and it takes around 8 minutes to switch from 1 region to another
