### ISSUE TITLE
Create many events - count not working

### ISSUE THREAD

**Issue by emikolajczak** [keycloak/keycloak-benchmark#45]
### Describe the bug

It seems that `count` parameter not working for `http://<host>/auth/realms/master/dataset/create-events?count=<count>`.
Regardless of whether it is set to 10 or other small amount, couple of thousands LOGIN events created.

### Version

17.0.0

### Expected behavior

Should be called exact amount of events as set in `count` parameter.

### Actual behavior

`count` parameter is not respected.

### How to Reproduce?

Try to call 10 events in example.

**Comment by ahus1** [comment]
@pedroigor / @emikolajczak - I see a PR has been merged for this issue, still this issue is open. 

I wonder if this issue can be closed/has been resolved. Thanks!
