### ISSUE TITLE
Dashboard for external Infinispan metrics

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#464]
Provide metrics from the external Infinispan to display them in the Grafana dashboard. 

Ideally there should be no changes to the existing dashboard. If we want to add additional metrics, they would appear blank in the standard dashboard, or we copy the dashboard.

**Comment by ahus1** [comment]
@pruivo: Martin and me looked at the setup via the Taskfile, and it already configures the metrics endpoints for Prometheus. 

When looking at the metrics, they are longer than in Keycloak, as Infinispan doesn't use the `names-as-tags`. Can we change that?

Thanks!

**Comment by pruivo** [comment]
> @pruivo: Martin and me looked at the setup via the Taskfile, and it already configures the metrics endpoints for Prometheus.
> 
> When looking at the metrics, they are longer than in Keycloak, as Infinispan doesn't use the `names-as-tags`. Can we change that?
> 
> Thanks!

yes, I can add that.

**Comment by pruivo** [comment]
@ahus1 PR here: https://github.com/keycloak/keycloak-benchmark/pull/465

**Comment by rmdes** [comment]
Wondering how to add User Events to default keycloak metrics, anyone have any clue ?

**Comment by mhajas** [comment]
@rmdes Please use another communication channel to ask your questions. Here are more details: https://www.keycloak.org/community This simplest option for you would be probably https://github.com/keycloak/keycloak/discussions. Also, please add more details on why you need it and what you want to achieve.
