### ISSUE TITLE
Gossip Router stability issues

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak-benchmark#473]
We found some connection issues between the Infinispan pods and Gossip Routers. This leads to some partitioned states where some messages go through and others don't. 

### Multiple Gossip Routers instances

The current implementation deploys 1 Gossip Router pod in each cluster. It brings the advantage of load balancing since each Infinispan pod will use both concurrently in a random fashion, and provides HA in case one of the Gossip Router pods fails. 

During tests, it was observed that some pods lost connection to one of the Gossip Routers leading to unstable communication. 

I propose to use a single Gossip Router globally to avoid unstable connections. 

### Multiple IPs for the same Gossip Router instance

Gossip Router expects a single connection for each Infinispan pod and we found some issues in the past (see [JGRP-2722](https://issues.redhat.com/browse/JGRP-2722)).

The Gossip Router is only able to use one connection to forward messages, meaning that the second connection is for receiving only. Also, the Gossip Router triggers a `SUSPECT` even when a connection is abruptly closed which leads to the "suspected" pod to removes from the view. TLTR: if one connection abruptly closes, the pod is removed from the view although there is a functional connection available. The pod is able to send data through the second connection Gossip Router is unable to send any data to it.

Fixing this in Gossip Router may improve the stability.

### Disable `SUSPECT` events

In the same context as above, it is possible to disable `SUSPECT` events on the connection closed. May be worth considering. Failure detection will be based on heartbeats (FD_ALLx)

### Skupper to the rescue?

Skupper (Red Hat Application Interconnect) allows two OCP clusters to connect. It is an alternative to using OCP Router to connect pods to the Gossip Router. If it is available in ROSA and it provides a single IP address for the Gossip Router, it may improve the stability of the cross-site connection.

**Comment by ahus1** [comment]
@pruivo - reading about Skupper, would this then be "if you want to use cross-DC with Kubernetes, you'll need to use Skupper"?

This might increase the complexity of the setup, and not all organizations would "allow" such a technology in their cluster (the same as they might not "allow" a service mesh): 

* It is a cluster wide change, and the person deploying Keycloak would need to persuade an infrastructure person to install and maintain it Skupper.
* Installing it might have an impact on the cluster itself, which would require testing and training
* Once you upgrade the Kubernetes cluster, you'll need to ensure it is still compatible with Skupper

Let's discuss later today if the use of this tool justifies those costs.

**Comment by pruivo** [comment]
> @pruivo - reading about Skupper, would this then be "if you want to use cross-DC with Kubernetes, you'll need to use Skupper"?

No! These tools, Skupper and [Submariner](https://submariner.io/) are tools with want to support in the Infinispan operator. See [JDG-6364](https://issues.redhat.com/browse/JDG-6364) (internal).

**Comment by ahus1** [comment]
Between the Infinispan pods and the gossip router, there are multiple instances which could terminate a TCP connection, and then the pod would need to (seamlessly) reconnect. 

* EC2 Load Balancers: Those do TCP load balancing and they have an idle timeout of 60 seconds (looked up on an example ROSA installation). So any configuration would need to do some TCP keepalive - possibly from the Infinispan pod initiating the connection. While this would prevent timeouts, reconnects should be graceful.
I didn't find a maximum lifetime for sessions.

* HAProxy: I didn't find a setting for a maximum lifetime for sessions, and also no keepalive settings. Pods and the nodes they run on might still restart on upgrades, and Infinispan pods should reconnect (seamlessly).

**Comment by belaban** [comment]
Wrt the connection between pods and the GossipRouter: you can enable heartbeats [1], so the connection will be left open, even when no regular traffic is encountered.
[1] https://issues.redhat.com/browse/JGRP-2634

**Comment by pruivo** [comment]
Linking some related GH issues for the Infinispan operator
https://github.com/infinispan/infinispan-operator/issues/1856
https://github.com/infinispan/infinispan-operator/issues/1857

**Comment by ahus1** [comment]
Current status: Wait for next version of Infinispan Operator, then retry with 2 Routers
