### ISSUE TITLE
Add a MAINTAINERS file to this repo

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#48]
### Description

While repositories like the main Keycloak repository have a MAINTAINER.md file, this repository hasn't. 

Without such a file one could only guess from the commit history who might be responsible to steer the development of this project. 

Looking at the commit history, the maintainers might be @mposolda and @pedroigor. 

### Motivation

Having a maintainer file would help to find out who is able/responsible to merge PRs, and who to contact about future plans and what is inside and outside of the scope of this project.

**Comment by pedroigor** [comment]
@ahus1 Thanks. Interesting coincidence ... I had a discussion with @stianst recently about aligning this repo with the guidelines of the Keycloak project.
