### ISSUE TITLE
Refresh token scenario - Single and A/P OCP clusters load test

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#489]
First results on Refresh Tokens (CPU overhead, use them together with login/logout to stress the shared Infinispan resources, Ratio 1:10 login/refresh)
```[tasklist]
### Tasks
```

**Comment by kami619** [comment]
Single OCP Cluster with internal infinispan and external Aurora DB Refresh token tests with 300 users-per-sec:

```
./benchmark.sh eu-central-1 --scenario=keycloak.scenario.authentication.AuthorizationCode \
 --server-url=https://keycloak-kakella-keycloak.apps.gh-mkanis.jfth.p1.openshiftapps.com \ 
--users-per-sec=300 --logout-percentage=100 --measurement=600 --realm-name=realm-0 \ 
--users-per-realm=10000 --ramp-up=180 --refresh-token-count=5 --refresh-token-period=5

```
Gatling results:
![image](https://github.com/keycloak/keycloak-benchmark/assets/3415105/2e43791f-aca3-4cdf-b840-9a57aa721e03)

Resource Utilization:
![image](https://github.com/keycloak/keycloak-benchmark/assets/3415105/7c36456f-a557-46fa-ace5-3dee28a7ec0c)


Load shedding observed with logs similar to this:

```
{"timestamp":"2023-08-14T20:51:12.303Z","sequence":11711,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.vertx.http.runtime.QuarkusErrorHandler","level":"ERROR","message":"HTTP Request to /metrics failed, error id: 0d83d50a-c326-4c02-9286-6432593b1176-4","threadName":"vert.x-eventloop-thread-1","threadId":82,"mdc":{"trace_flags":"00","trace_id":"ba4dd3e838c294e3a88499af48b50701","span_id":"7ee6379f9dae297c"},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"java.util.concurrent.RejectedExecutionException","message":null,"frames":[{"class":"org.jboss.threads.RejectingExecutor","method":"execute","line":38},{"class":"org.jboss.threads.EnhancedQueueExecutor","method":"rejectQueueFull","line":2127},{"class":"org.jboss.threads.EnhancedQueueExecutor","method":"execute","line":821},{"class":"io.vertx.core.impl.ContextBase","method":"executeBlocking","line":150},{"class":"io.vertx.core.impl.DuplicatedContext","method":"executeBlocking","line":138},{"class":"io.vertx.core.impl.ContextInternal","method":"executeBlocking","line":153},{"class":"io.vertx.core.Vertx","method":"executeBlocking","line":597},{"class":"io.vertx.ext.web.impl.BlockingHandlerDecorator","method":"handle","line":47},{"class":"io.vertx.ext.web.impl.BlockingHandlerDecorator","method":"handle","line":33},{"class":"io.opentelemetry.javaagent.instrumentation.vertx.RoutingContextHandlerWrapper","method":"handle","line":36},{"class":"io.opentelemetry.javaagent.instrumentation.vertx.RoutingContextHandlerWrapper","method":"handle","line":21},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284}
```

**Comment by kami619** [comment]
Single OCP Cluster with internal infinispan and external Aurora DB Refresh token tests with

- 200 users-per-sec
- 1:5 - login:refreshToken request ratio

```
./benchmark.sh eu-central-1 --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=https://keycloak-kakella-keycloak.apps.gh-mkanis.jfth.p1.openshiftapps.com --users-per-sec=200 --logout-percentage=100 --measurement=600 --realm-name=realm-0 --users-per-realm=10000 --ramp-up=180 --refresh-token-count=5 --refresh-token-period=5

```

Gatling results:
![image](https://github.com/keycloak/keycloak-benchmark/assets/3415105/523ca3dc-1105-4bf3-8575-5b604eb321ff)

Resource utilization:
![image](https://github.com/keycloak/keycloak-benchmark/assets/3415105/214679d8-4892-4d7b-be35-e2295112435b)

**Comment by ahus1** [comment]
@kami619 - thank you for sharing these results. Could you please also share the dashboard of the Infinispan statistics? I would be most interested in the JGroup thread statistics. Thanks!

**Comment by kami619** [comment]
> @kami619 - thank you for sharing these results. Could you please also share the dashboard of the Infinispan statistics? I would be most interested in the JGroup thread statistics. Thanks!

sure thing, I can add the screenshots for ISPN dashboards too

**Comment by kami619** [comment]
Active-Passive refresh token tests were performed with both 1:5 (login:RefreshToken) ratio as well as 1:10 (login:RefreshToken) ratio., in both cases we observed for the cluster with 6 Keycloak Pods and 8 CPU limit for each pod and with external ISPN server and external Aurora PostgreSQL db and liveness and readiness probes disabled,

 - The system scales well up until an overall limit of 1500 global req/s throughput and starts to load shed with 503 server side exception handling.
 - When OTEL is enabled, the regular Vert.x metrics endpoint gets rejected due to connection pool congestion with overall saturation and results in some errors on the server side.
 - We don't see aggressive CPU throttling due to the load shedding behavior of Keycloak however we see response times go above 2000 ms during these periods as shown in the below screenshot of the SLO dashboard during a load run when the load shedding happened.
 - Increase in refresh-token-count is proportional to the time at which the load shedding behavior happens and it seems to happen earlier as the count of refresh token's increase.

![screencapture-grafana-apps-gh-mhajas-7vw1-p1-openshiftapps-d-R3kK-894z-authentication-code-slo-2023-08-17-13_33_26](https://github.com/keycloak/keycloak-benchmark/assets/3415105/df7fd915-319b-4608-8c29-1d279a1842cf)

**Comment by kami619** [comment]
8/23 update was to repeat the tests that show slowness in response times once we start to see load shedding and upon confirming the behavior log a separate ticket to investigate the root cause for the slowness in response times.

**Comment by ahus1** [comment]
Completion criteria for this issue: 

* Understand high response times, theory: When request queue is full (1000 entries), newly queued requests need to wait for their turn to complete
* Have a CPU calculation base for refresh tokens

**Comment by kami619** [comment]
- We found the 175 users-per-sec to be the optimum supported run rate for a 6 pod cluster with 8 CPU limit per pod which translates to 126 refresh tokens per vCPU or 378 refreh tokens per second per vCPU in a 3 pod clusters to match the calculations [here](https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/report/rosa-benchmark-key-results#calculation-example).

full results for the 175 users-per-sec can be found [here](https://drive.google.com/file/d/1JmYdsKMMWYt1zaccwzENOCacCKAjqw72/view?usp=drive_link). 

- Beyond that we start to hit the limit of the system and at about 200 users-per-sec we were able to reproduce the requests being queued situation and that results in higher response times and load shedding starts to happen on the Keycloak server side.

Overall I think we achieved the objective of the ticket, if it lines up with the expectation we can close this one.

We have created subsequent tickets to,
- https://github.com/keycloak/keycloak-benchmark/issues/516
- https://github.com/keycloak/keycloak-benchmark/issues/517
- https://github.com/keycloak/keycloak-benchmark/issues/518
