### ISSUE TITLE
Kerberos\Spnego support for AuthorizationCode scenario

### ISSUE THREAD

**Issue by YuriB9** [keycloak/keycloak-benchmark#491]
### Description

Does current implementation of AuthorizationCode scenario support SPNEGO auth?

Currently, I always receive "HTTP 401 Unauthorized" + "Kerberos is not set up.  You cannot login." :
`15:35:10.909 [DEBUG] i.g.h.e.r.DefaultStatsProcessor - Request 'Browser to Log In Endpoint' failed for user 2: status.find.is(200), but actually found 401`

But the same Kerberos config perfectly works for other applications...

### Motivation

To benchmark keycloak performance via LDAP\Kerberos auth.

**Comment by ahus1** [comment]
Hi @YuriB9 - I'm not aware of anyone using the Keycloak Benchmark project to test Kerberos authentication, yet. 

AFAIK 401 (not authenticated) is the expected response in a Kerberos negotiation, as in the next step the client will send a token.

I suggest you search for resources on the Internet about Gatling and Kerberos. One of these resources might be this email thread: https://groups.google.com/g/gatling/c/4L_OofnOQy0

Once you have it up and running, I'd be happy if you could share the code and a documentation snippet either in this issue, or in a pull request to the project. 

Please let me know if you want to keep this issue open, or if you want to close it.

**Comment by ahus1** [comment]
Closing this issue as there wasn't a reply. Please comment if I should re-open the issue.
