### ISSUE TITLE
Update ROSA scalability workflow to commit the result numbers to github

### ISSUE THREAD

**Issue by andyuk1986** [keycloak/keycloak-benchmark#496]
1. Need to update the workflow to commit the result numbers to github repository as it was doing the Keycloak Scalabioity Workflow.
2. Schedule the workflow to run every day.

**Comment by andyuk1986** [comment]
Created 2 PRs:
https://github.com/keycloak/keycloak-benchmark/pull/501

Updated the workflow to save in conclusion JSON also the workflow execution date, so that when the aggregated report is released it is readable and it is visible the parameters for each run. Also created a workflow for scheduled run of ROSA scalability benchmark (the same as for Keycloak benchmark run, i.e. from Mon-Fri at 07.00UTC time).

https://github.com/keycloak/keycloak-benchmark/pull/500

Updated the workflow to add ROSA scalability benchmark results to aggregated-benchmarks tag. I haven't touched the existing result files, just added the new one and it will look like:
```
[
    {
        "Execution date": "2023/08/23",
        "Memory usage for sessions": {
            "Active sessions per 500 MB memory per Pod in 3 Pod cluster": 99919
        },
        "CPU usage for user logins": {
            "User Logins per second per 1vCPU per Pod in 3 Pod cluster": 45
        },
        "CPU usage for client credential grants": {
            "Client Credential Grants per second per 1vCPU per Pod in 3 Pod cluster": 463
        }
    },
    {
        "Execution date": "2023/08/22",
        "Memory usage for sessions": {
            "Active sessions per 500 MB memory per Pod in 3 Pod cluster": 166143
        },
        "CPU usage for user logins": {
            "User Logins per second per 1vCPU per Pod in 3 Pod cluster": 46
        },
        "CPU usage for client credential grants": {
            "Client Credential Grants per second per 1vCPU per Pod in 3 Pod cluster": 482
        }
    }
]
```

**Comment by andyuk1986** [comment]
Updated the PR to include UUID for benchmark run and the timestamp specifying the start time of the benchmark. Sent an additional PR for `result-data` with updated result file name. The PR is: https://github.com/keycloak/keycloak-benchmark/pull/503

**Comment by mhajas** [comment]
Here is a scalability benchmark run that should upload the results to `result-data` branch.

**Comment by andyuk1986** [comment]
After permission addition to aggregate trigger (thanks @mhajas ) the first results are released to `aggregated-benchmark` tag.
The result for latest run can be found here: https://github.com/keycloak/keycloak-benchmark/releases/tag/aggregated-benchmarks
