### ISSUE TITLE
Unsupported Operation Exception when running benchmark from the CLI

### ISSUE THREAD

**Issue by knighthedspi** [keycloak/keycloak-benchmark#499]
### Describe the bug

When running benchmark version 0.10 from the CLI with the below command
```bash
 bash kcb.sh  --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=http://localhost:8180 --realm-name=myrealm --username=user-0 --user-password=user-0-password --client-id=MY_CLIENT --client-secret=MY_SECRET--client-redirect-uri=http://localhost --scope=openid profile offlice_access
```
I received below errors from gatling report
```
j.l.UnsupportedOperationException: Can't connect to IPv6 remote localhost/[0:0:0:0:0:0:0:1]:8180 + from IPv4 local one /100.127.100.1:0
j.l.UnsupportedOperationException: Can't connect to IPv6 remote localhost/[0:0:0:0:0:0:0:1]:8180 + from IPv4 local one /100.64.0.1:0
```
It worked well on previous benchmark versions.

### Version

Keycloak: 22.0.1, benchmark: 0.10-SNAPSHOT

### Expected behavior

Works well like previous versions without error

### Actual behavior

I received below errors from gatling report
```
j.l.UnsupportedOperationException: Can't connect to IPv6 remote localhost/[0:0:0:0:0:0:0:1]:8180 + from IPv4 local one /100.127.100.1:0
j.l.UnsupportedOperationException: Can't connect to IPv6 remote localhost/[0:0:0:0:0:0:0:1]:8180 + from IPv4 local one /100.64.0.1:0
```

### How to Reproduce?

Running the benchmark version 0.10-SNAPSHOT from the CLI
https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/run/running-benchmark-cli

**Comment by ahus1** [comment]
Looking the CLI, the parameters for `--scope` probably need quoting, so it would read:

```
--scope="openid profile offlice_access"
```

lease double-check, I haven't tested this myself yet. Setting the environment variable `RUNNER_DEBUG` to `1` should log additional information from the bash script to debug if the value is passed correctly. 

About the localhost issue: Something seems to be off with IPv6 vs. IPv4 as outlined in the error message. Use the CLI option `--log-http-always` to show all responses received from Keycloak. It seems that there is some redirect to a port `8180` happening, which seems to be specific for your setup.

**Comment by ahus1** [comment]
It seems this was a side effect introduced in #434 by @ddurham2 when a system doesn't have a public IPv6 interface, but has resolves localhost with an IPv6 address. 

https://github.com/gatling/gatling/blob/6dbac4c2740f3200cbefcc7b1f7f36bb2732c8e3/gatling-http-client/src/main/java/io/gatling/http/client/impl/DefaultHttpClient.java#L776-L783

I've pushed a change to wrap the line `default = default.useAllLocalAddresses` in a new CLI option `use-all-local-addresses` which should restore the previous default. 

Please give it a try and let me know if this works for you again.

**Comment by knighthedspi** [comment]
Thanks. I tried and confirmed it works well.

**Comment by ahus1** [comment]
Thank you @knighthedspi  for testing this change!
