### ISSUE TITLE
Duplicate logback.xml and logback-test.xml configuration files leading to confusion

### ISSUE THREAD

**Issue by davoustp** [keycloak/keycloak-benchmark#53]
### Describe the bug

The project bundles two almost identical `logback.xml` and `logback-test.xml` files into the same shaded jar.

As a result, logback always uses the `logback-test.xml` file - as this is rightfully the expected behaviour to manage test-related logging configuration - ignoring the other file in the process.

Not exactly sure how the test-focused `logback-test.xml` file is used in this context (maybe while debugging scala-scenarii?), but differences are minor (diff below):

```
12d11
<         <immediateFlush>false</immediateFlush>
17c16
<             <pattern>%d{HH:mm:ss} %msg%n%rEx</pattern>
---
>             <pattern>%msg%n%rEx</pattern>
38,41d36
<     <!--logging for dataset-->
<     <logger name="org.keycloak.benchmark.performance.dataset" level="INFO" additivity="false">
<         <appender-ref ref="CONSOLE_MSG_ONLY"/>
<     </logger>
```

We have a few options:
* merge them into the `logback.xml` file and remove the `logback-test.xml` file
* keep them but move the `logback-test.xml` file to `src/test/resources` as files in this directory are included in the classpath only for `test`-related maven scopes (this is where `logback-test.xml` should actually belong)

I'd suggest merging as having distinct files is always confusing for newcomers, especially that the differences are minor (pattern for `CONSOLE_MSG_ONLY` with or without timestamp, immediate flush on/off, and `org.keycloak.benchmark.performance.dataset`-related logging settings). 

Thoughts?
I'll submit a PR when agreement is reached.

### Version

18.0.0

### Expected behavior

Modifying the main `logback.xml` file should be taken into account when running the benchmark scenarii.

### Actual behavior

Modifying the main `logback.xml` file is entirely ignored when running the scenarii.

### How to Reproduce?

This can be demonstrated with start-time logging by adding option `--logback.statusListenerClass=ch.qos.logback.core.status.OnConsoleStatusListener` to the `kcb.sh` invocation:
```
10:15:54,704 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [jar:file:/Users/pdavoust/Documents/Temp/keycloak-tenant-benchmark/gatling/keycloak-benchmark-0.7-SNAPSHOT/lib/keycloak-benchmark-0.7-SNAPSHOT.jar!/logback-test.xml]
10:15:54,753 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@47ef968d - URL [jar:file:/Users/pdavoust/Documents/Temp/keycloak-tenant-benchmark/gatling/keycloak-benchmark-0.7-SNAPSHOT/lib/keycloak-benchmark-0.7-SNAPSHOT.jar!/logback-test.xml] is not of type file
```

This shows exactly which configuration file logback uses, as shown above.

**Comment by kami619** [comment]
I think its a fair idea to have a single logback.xml to keep things simple and currently we dont have a src/test directory so, it would be good to just maintain one logback.xml to avoid confusion.

**Comment by ahus1** [comment]
@davoustp - I agree with Kamesh, the `logback-test.xml` should be removed. The "logging for dataset" is only relevant for the module build to run inside Keycloak, so these classes will never be present within the JVM of the benchmark. 

Therefore there are no relevant changes in `logback-test.xml` and it can be removed. Please create a PR and I'll merge it right away.

**Comment by davoustp** [comment]
@ahus1 - one thing, though: the main `logback.xml` file sets the `immediateFlush` flag to `false`, while the `logback-test.xml` does not (and default is `true`, see https://logback.qos.ch/manual/appenders.html#immediateFlush).

So it may impact debugging: step-by-step debugging may not see the log written to the console in synchronous manner.
Ok with that?

**Comment by ahus1** [comment]
Looking at a real load test, I'd assume that Logback wouldn't log anything anyway (exception maybe errors), so the performance impact on enabling the immediate flush (with the default) it would be minimal. 

I lack experience with Logback and this flush feature for debugging; if you'd recommend to enable it, I'll follow your advice.

@davoustp - Please let me know if you'd like to update the PR, or merge it as is.

**Comment by davoustp** [comment]
> Looking at a real load test, I'd assume that Logback wouldn't log anything anyway (exception maybe errors), so the performance impact on enabling the immediate flush (with the default) it would be minimal.

I agree. gatling logs very few lines (periodic performance reports only) so attempting to optimize logging is useless.

> I lack experience with Logback and this flush feature for debugging; if you'd recommend to enable it, I'll follow your advice.

When immediate flush is disabled, then the logging becomes asynchronous: some logs items may be buffered until logback decides to flush it to the output. So when step-by-step debugging, it may be very confusing as you step over a logging statement but it's not written out...
So yes, I'd suggest reverting to the default behaviour (immediate flush enabled).

Updating PR.
