### ISSUE TITLE
Throw an error when Cross-DC operations fail (in SYNC mode)

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#531]
When running in SYNC mode in Cross-DC, a write to the other DC can fail. 

The current (default) behavior: 
* The request will time out
* The call returns to the caller where the data is the current site, but not the remote site

Due to that, the current and the remote site are then out of sync, so a session might not exist in the remote DC, or might not have been deleted in the remote DC. 

When discussion this with @pruivo, I understand that this behavior can be changed, so that there is an exception. When there is an exception, the expectation is that no changes written to the local Infinispan (both the internal and the external Infinispan). 

With this change, there will be no longer the need to issue a state transfer when single writes fail. It will only be necessary to do a state transfer when the other side becomes offline.

This issue is to 

* Check if the understanding of the current and target state is correct
* Reconfigure Infinispan and Keycloak to match the target state
* Run tests to verify the new target behavior

Possible edge cases: 

* The writes to Infinispan are in a second phase of the transaction which is `enlistAfterCompletion` - due to that, a write to the database might complete including a commit, and then the write to Infinispan fails. This might happen when changing a client or user, but shouldn't happen when logging in, refreshing tokens and logging out as those are read-only for the database.

**Comment by ahus1** [comment]
@pruivo / @mhajas - this came up during a discussion with @stianst. Can you please review if this issue makes sense? Please reach out for a chat/call if that makes sense. Thanks!

**Comment by pruivo** [comment]
> When there is an exception, the expectation is that no changes written to the local Infinispan (both the internal and the external Infinispan).

That is not true. Keycloak source code first updates the embedded Infinispan and then updates the external Infinispan. Even if the exception is thrown, the embedded Infinispan caches would be out of sync.
See https://github.com/keycloak/keycloak/blob/81aa588ddc33de94884568aef0f9d46868ad8232/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/InfinispanChangelogBasedTransaction.java#L171-L177

**Comment by ahus1** [comment]
> Keycloak source code first updates the embedded Infinispan and then updates the external Infinispan.

Thank you for investigating this. This describes the target behavior I would like to see. Looking at the code, I assume this can be fixed in Keycloak.
