### ISSUE TITLE
Make Infinispan failure detection timeout configurable

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#532]
When running in SYNC mode, and the Gossip Router between two sites fails, there is currently a timeout of ~40 seconds. 

To make it workable for customers, it would be good to make this configurable to get in the area of 10 to 15 seconds.

**Comment by pruivo** [comment]
@ahus1 I'm unable to edit the title... Can you change `SYNC timeout` to `failure detection timeout` to be more accurate pls?

**Comment by ahus1** [comment]
Done!

**Comment by ahus1** [comment]
@pedroigor - could you please update the helm charts once the operator has been released? Thanks!
