### ISSUE TITLE
State transfer automation

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#533]
* Meeting - minutes available internally: https://docs.google.com/document/d/1Dnx8y7KkHxDEnt52R1iDylEHJaB6jvF1o-RQIRFhwo0/edit

* Minimal recipe to trigger a manual state transfer. As discussed in the meeting, a good candidate for this would be the Batch CR, see https://infinispan.org/docs/infinispan-operator/main/operator.html#batch-cr 

Out of scope: Detect when a state transfer is necessary

**Comment by pruivo** [comment]
Upstream JIRA: https://issues.redhat.com/browse/ISPN-12989

**Comment by ahus1** [comment]
Done: Steps for Async

Pending: Steps for Sync

**Comment by ahus1** [comment]
Docs are now complete for the "operational procedures".
