### ISSUE TITLE
Run functional cross-site testing

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#535]
Possible tests (to be extended): 

* logging in one site, using the session the side
* logging out one site, verifying the session is gone on the side
* modifying a client on one side, verifying the change is available on the other side (even if it was already cached on the other side)
* changing a user's password on one side, verifying the change on the other side

**Comment by pruivo** [comment]
@ahus1 will these tests be added to Keycloak test suite? 
Are there other scenarios planned?

**Comment by ahus1** [comment]
@pruivo - this is a good question and this needs to be discussed. If we think the tests should run on two OpenShift clusters with Cross-DC setup including an Aurora database, the standard Keycloak testsuite might be difficult to run against that setup. The three scenarios listed above are only the first ones that came to my mind, and I expect there to be more. As usual, we would need to prioritize them :-)

**Comment by kami619** [comment]
[Overview](https://docs.google.com/document/d/1qguQXmMq_-KfH6iMXZO1vkgPjwY_hjgH3DNvXR6baBI/edit#heading=h.9g6nvpuaon2e) of the current Cross DC functional tests. Me and Tomas plan on reviewing these test cases and picking one of them to be executed against a real Cross DC environment. This would be a larger effort, so would be creating needed sub-tasks from this parent ticket.

**Comment by kami619** [comment]
From Async point of view, would be interested in out of date caches based scenarios.

**Comment by kami619** [comment]
We plan to create and run a smoke test suite to determine the health of a cross-site functionality before we go ahead and automate that.

**Comment by kami619** [comment]
We were able to create a functional smoke test suite and test the real cross dc cluster with those tests. We are continuing the creation of an automation tests suite around that in #584 with help of @martin-kanis. Give this, I think the intent of the ticket is achieved.
