### ISSUE TITLE
Re-evaluate Route53 loadbalancing

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#536]
DNS based failover takes 45-120 seconds + corner case DNS caching making it unpredictable

Talk to Red Hat internal people to get input on Cloudflare or Akamai usage.

Other reasons to use a CDN/proxy instead of DNS: Deflect denial of service, WAF/security, performance, load shedding, ...

We might then use AWS Global Accelerator in our setup.

We also might need a way of the active site preventing the stale passive site to become active accidentially, and implement something like https://en.wikipedia.org/wiki/STONITH - see #534 

More reading: https://cloud.redhat.com/blog/global-load-balancer-approaches

Internal issue which might contain information on how to set it up: CIAM-2516

**Comment by ahus1** [comment]
For a Multi-AZ szenario (not multi-region), a ELB might be more cost effective and simpler to set up: https://aws.amazon.com/elasticloadbalancing/

**Comment by ryanemerson** [comment]
> For a Multi-AZ szenario (not multi-region), a ELB might be more cost effective and simpler to set up: https://aws.amazon.com/elasticloadbalancing/

I don't think using an ELB is an option as it does not support exclusive failover on health check failures and seemingly it will continue to forward requests to unhealthy endpoints if no healthy ones exist. See below from the [AWS knowledge centre](https://repost.aws/knowledge-center/elb-make-weighted-target-groups-for-alb).

> Note: The Application Load Balancer distributes traffic to the target groups based on weights. If all targets in a target group fail health checks, then the Application Load Balancer doesn't route or fail over the requests to another target group. If a target group has only unhealthy registered targets, then the load balancer nodes route requests across its unhealthy targets. When all the targets in a target group are unhealthy, don't use a weighted target group as a failover mechanism.

**Comment by ryanemerson** [comment]
It's possible to use the AWS Global Accelerator to workaround the limitations of a DNS based approach.

# Architecture
An accelerator requires a "Listener" to be defined that dictates which ports traffic can be received on. The Listener then routes traffic to an "Endpoint Group" defined per region, which specifies the Endpoints that traffic should be routed to. Each Endpoint definition has a weight associated with it, with 100 determining that all traffic should be routed to the endpoint and 0 meaning no traffic should be routed to the endpoint.

Endpoint failover works as follows:

>If there are no healthy endpoints in an endpoint group that have a weight greater than zero, Global Accelerator tries to failover to a healthy endpoint with a weight greater than zero in another endpoint group. For this failover, Global Accelerator ignores the traffic dial setting. So if, for example, an endpoint group has a traffic dial set to zero, Global Accelerator still includes that endpoint group in the failover attempt.

Therefore, we define our primary cluster endpoint to have a weight of 100 and the backup cluster to have a weight of 0. This means that in the event of the primary AZ failing, all traffic will be handled by the backup cluster hosted on a different AZ. 

Further reading:
- [Deploying multi-region applications in AWS using AWS Global Accelerator
](https://aws.amazon.com/blogs/networking-and-content-delivery/deploying-multi-region-applications-in-aws-using-aws-global-accelerator/)
- [Traffic management with AWS Global Accelerator
](https://aws.amazon.com/blogs/networking-and-content-delivery/traffic-management-with-aws-global-accelerator/)

# Implementation
https://github.com/keycloak/keycloak-benchmark/pull/586

Summary:
1. A Network Load Balancer is exposed by each of the ROSA clusters via a Kubernetes Service of type LoadBalancer with the annotation `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"`.

  - We can't use an Application Load  Balancer as this requires a VPC with at least two availability zones.
  - We cannot use the Load Balancer of the ROSA cluster itself as the health checks will only fail if the cluster goes down, not the Keycloak deployment.

2.

**Comment by ryanemerson** [comment]
After further experimentation, it seems the Global Accelerator is not suitable for an Active/Passive configuration without additional enhancements to the architecture described above. This is because the accelerator continues to route some traffic to the Primary ROSA cluster with a weight of 100 even when all nodes are unhealthy. From the [AWS docs](https://docs.aws.amazon.com/global-accelerator/latest/dg/about-endpoints-endpoint-weights.unhealthy-endpoints.html):

>If there are no healthy endpoints in an endpoint group that have a weight greater than zero, Global Accelerator tries to failover to a healthy endpoint with a weight greater than zero in another endpoint group. For this failover, Global Accelerator ignores the traffic dial setting. So if, for example, an endpoint group has a traffic dial set to zero, Global Accelerator still includes that endpoint group in the failover attempt.

>If Global Accelerator doesn't find a healthy endpoint with a weight greater than zero after trying the three closest endpoint groups (that is, AWS Regions), it routes traffic to a random endpoint in the endpoint group that is closest to the client. That is, it fails open.

To workaround ^ limitation, it is possible to create an AWS Lambda that flips the weight of the Primary and Backup endpoints on failover, or removes the failed Primary endpoint entirely. This requires a CloudWatch alarm to be created when unhealthy nodes are detected by the NLB, which in turn is used to trigger a Lambda that checks that all nodes within the NLB are down and then updates the Accelerator configuration accordingly. 

For the initial Active/Passive implementation, we will proceed with Route53 based failover/loadbalancing.

**Comment by ahus1** [comment]
With #594 it should be good enough for the initial A/P release.
