### ISSUE TITLE
openshift task generates incorrect output

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak-benchmark#549]
### Describe the bug

When running `./provision/openshift/task` there is following like output:
```
[keycloak] NOTES:
[keycloak] Keycloak will be available on https://keycloak-vramik-keycloak.apps.gh-keycloak.jfth.p1.openshiftapps.com
[keycloak]   user: admin
[keycloak]   password: admin
```

the password is not correct.

### Version

0.10-SNAPSHOT

**Comment by ahus1** [comment]
Hi @vramik - thank you for spotting and reporting this. 

The template for your output is in `provision/minikube/keycloak/templates/NOTES.txt` and you can use the usually Helm/Go templating to replace this constant in the template. 

When running on GitHub and logging the real password, it needs to be masked as `***`. 

GitHub actions has a feature for that that a process can log the to-be masked contents, and we used it for example in `rosa_oc_login.sh`. See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-a-log for the full docs.

```
echo "::add-mask::${ADMIN_PASSWORD}"
``` 

IMHO it makes sense to do this as close as possible to reading the password. When deploying Keycloak to OpenShift, this is done as part of the Task file, and I don't have a recipe for this at hand. I'd be happy to hear your ideas. 

Thanks!

**Comment by ahus1** [comment]
Masking of the password already done here: https://github.com/keycloak/keycloak-benchmark/blob/21742175705192e9335a3d4a43d84811563b9e0a/.github/actions/rosa-cli-setup/action.yml#L50-L52
