### ISSUE TITLE
Configure conflict resolution for ASYNC

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#551]
Conflict resolution in cross-DC is only available in ASYNC mode of Infinispan.

Current default behavior: "sort by site name, first one wins the write"

Depending on the different caches, there might be different strategies which should be applied.  For this issue, we'll only pick from the existing strategies only (no custom strategies).

**work cache, login failures, ...** 
* keep the entry (use newer entry?)

**sessions, single use, ...:** 
 * if there is a conflict, drop the entry

_Originally posted by @ahus1 in https://github.com/keycloak/keycloak-benchmark/issues/524#issuecomment-1709679068_

**Comment by ahus1** [comment]
@pruivo - I had a look at the docs here: 

* https://infinispan.org/docs/stable/titles/xsite/xsite.html#cross_site_merge_policies
* https://docs.jboss.org/infinispan/14.0/apidocs/org/infinispan/xsite/spi/XSiteMergePolicy.html

I assume that we'll need to define one strategy for each cache which is in the external Infinispan?

Could you prepare a suggestion for each cache with a safe side fallback? 

cc: @mhajas

**Comment by pruivo** [comment]
Yes, each cache has its own conflict resolution strategy. Not sure if I'm the right person to do it since it is not clear to me what each cache requires.

**Comment by ahus1** [comment]
Here my attempt: 

* sessions / authenticationSessions / offlineSessions / clientSessions / offlineClientSessions / actionTokens: ALWAYS_REMOVE (as no session / no token is the safe side fallback) 
* loginFailures: default (ideally they would be merged, but that's out of scope here)
* work: default (mostly as I can't think of anything better / anything that would make sense) 

@mhajas - what would you think of this?

**Comment by mhajas** [comment]
`actionTokens` should not use `ALWAYS_REMOVE`. Sometimes we store there information that something was used and then if someone wants to use it again, it is found in the cache and claimed invalid. Removing it during a conflict resolution may break this. This can result in, for example, OTP code reuse: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/credential/OTPCredentialProvider.java#L122
