### ISSUE TITLE
Probes - What to watch/monitor for a running cross DC setup and that none of the parts has failed

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#578]
When customers run the setup in their environment, they should point their monitoring to specific URLs to see if everything is up and running as expected. 

Examples: 
* URL on loadbalancer
* URL on Keycloak Route (one on each Cluster)
* URL on Infinispan (one on each Cluster)
* URL on the Gossip Router
* ...

Those could be the health endpoints.

**Comment by kami619** [comment]
@ahus1 

https://github.com/prometheus/blackbox_exporter

I found this prometheus exporter which is designed to probe the liveness of a specific target url, which in this case could be a list of probes or health check endpoints of our architecture. This would also allow the end user to visualize the outcome of these HTTP probes in a Grafana dashboard. Let me know your thoughts on this.

**Comment by ahus1** [comment]
Yes, that blackbox exporter is a popular choice for those items. Still, let's first find the URLs. Giving it a bit more thoughts, there might be more things than just URLs to monitor. Things might include: 

* Different `status` items on deployments/Operator CRs
* Checking Infinispan if a correct cluster has been formed, and cross-site is all working
* Checking if the number of deployed Keycloak Pods matches the number of nodes discovered by Keycloak's infinispan
* ...

In the end we want to have a list of check that are either "red" (something wrong) or "green" (everything is fine).
