### ISSUE TITLE
Metrics - Most important SLI to determine that Keycloak is healthy

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#579]
For customers to be able to run Keycloak in a production environment, they should have an overview of the ~10 metrics on both Keycloak an Infinispan so they can be both confident that their system is running ok, and anyone supporting their setup can ask for those metrics (eventually a dashboard).

Example include: 
* Number of cache entries per Keycloak and Infinispan pod
* Memory and CPU usage per pod
* JGroup thread usage
* Cache hit ratio + cache size for local caches 
* ...

**Comment by kami619** [comment]
I have created a starter list for such metrics and shared the doc with @pruivo for additional review and once this is ironed out, I can work on getting this into the docs.

**Comment by ahus1** [comment]
Next step: Write one page in KCB describing the three SLIs and why we chose them, a human readable explanation per metric, with their metric name and relevant tags in Prometheus.
