### ISSUE TITLE
expose the infinispan http endpoint in the external infinispan deployment

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#582]
### Description

We would need access to both the infinispan console as well as the rest endpoint to be able to write reproducible automation to READ, DELETE cache stats.

one we way found to be working was to add a expose yaml block to the Infinispan CRD as shown below

```
expose:
    host: keycloak-kamesh-keycloak.apps.XXXXXX.openshiftapps.com
    type: Route
```

**Comment by pruivo** [comment]
That seems correct to me. `host` is optional and, if not set, it is generated automatically based on the namespace and service name.
