### ISSUE TITLE
Horreum: Define the Schema for uploaded json

### ISSUE THREAD

**Issue by andyuk1986** [keycloak/keycloak-benchmark#633]
- Schema should be defined in Horreum for the uploaded json. 
- At the moment of creation the schema will include the Labels for the entries calculated in ROSA benchmark workflow, i.e. the CPU and memory related information that we currently generate.

Later the schema/JSON file will be updated with additional information (environment related data, latencies, etc) which is necessary for reporting/change detection.

**Comment by andyuk1986** [comment]
I have created a new schema in Horreum (first wanted to reuse the one created by Kamesh a while ago, but there were runs already connected to it, so created new one). Created the first 3 labels based on the data we have in json. 
The schema could be found here: https://horreum.corp.redhat.com/schema/188#labels
I will close this task, and will be added labels to schema according to work progress.

P.S. Seems that I would need to create a new JSON file in parallel with the one that is created during benchmark run, as here I would need to have a proper JSON schema with easy to read keys for being to access them from the Horreum schema (it uses PostgreSQL JSON Path Language).

**Comment by ahus1** [comment]
@andyuk1986 - we have a JSON schema, it would be good to eventually mirror it as a file in the public repository. 

There are no follow-up processes using the current JSON, so feel free to either the existing one or create a new one in parallel while you are experimenting. 

Long term there should be only a single JSON file, and the old JSON files should be converted to the new structure (assuming the new structure would be very different). 

Please discuss the new JSON structure with the team and also some people experienced with Horreum, as it could safe you one or two iterations in the coding process.
