### ISSUE TITLE
Horreum: Implement GH action to retrieve an offline auth token & Publish the simple JSON report

### ISSUE THREAD

**Issue by andyuk1986** [keycloak/keycloak-benchmark#634]
Implement a GH action for retrieving offline token and based on that token publish the  JSON file to Horreum.

**Comment by andyuk1986** [comment]
At the moment it is not possible to implement this. Our Corporate Horreum where we wanted to publish the data is located under VPN so it is not accessible from outside. We have discussed another option of publishing the data from Github, i.e. using Jenkins (maybe nightly) job for downloading the data from Github and publishing it to Horreum. 
There could be another option -> we have introduced our environment and requirements to Horreum team and they will be having JIRA on their side for us, so maybe they will be able to offer a better option.

**Comment by ahus1** [comment]
Follow-up task: #656
