### ISSUE TITLE
Horreum: Include latencies from Gatling reports

### ISSUE THREAD

**Issue by andyuk1986** [keycloak/keycloak-benchmark#635]
- Implement logic for retrieving the latencies information from the Gatling report and put it to JSON file. 
- Update the schema in Horreum correspondingly to include Labels for newly created fields.

**Comment by andyuk1986** [comment]
So the first part of this task is done: the JSON now contains the statistics from the gatling reports. Please find attached the generate JSON from my example run attached. 

[result-20240122-104743-7af59ee9-df49-4d73-94ce-fadd6dd31757.json](https://github.com/keycloak/keycloak-benchmark/files/14010080/result-20240122-104743-7af59ee9-df49-4d73-94ce-fadd6dd31757.json)

Will be working on the second part of the task, i.e. Horreum upload and schema update for Horreum .

**Comment by ahus1** [comment]
Thank you for preparing this document, it now contains the context that we need to analyze runs.

Some observations: 
* Some values that are boolean or numbers shouldn't quotes
* For now, as discussed and agreed, keep all information in one file until we know how this works with Horreum
* Consider one styling of attribute names (possibly "camelCase" as this is the Gatling format), as this would be difficult to change afterwards

**Comment by andyuk1986** [comment]
PR is sent: https://github.com/keycloak/keycloak-benchmark/pull/696
