### ISSUE TITLE
Expired X-Site token prevents the work of the Infinispan Operator

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#663]
### Describe the bug

As described in #607, I was able to reproduce the problem and the error, that the operator didn't restore the deployments on the primary cluster, even without the load. 

I found the following error message in the logs of the operator: 

> ERROR	controllers.Infinispan	could not connect to remote location URL	{"infinispan": "runner-keycloak/infinispan", "URL": "openshift://api.gh-keycloak2-b.wasw.p1.openshiftapps.com:6443", "error": "Unauthorized"}

The root cause is that the token for the other cluster generated in https://www.keycloak.org/high-availability/deploy-infinispan-kubernetes-crossdc is valid for only 60 minutes. 

### Version

main

**Comment by ahus1** [comment]
Once the token was regenerated and put into corresponding secret, and the Infinispan Operator was restarted, the Infinispan Operator restored the deployments as expected. 

A longer duration is possible by adding the duration to the token creation request. I was able to even specify a duration of one year. The duration of the token is stored in the token (it is a JWT token that can be decoded using the usual tools).

```
kubectl create token -n runner-keycloak xsite-sa --duration=48h
```

Suggested next steps: 
* Verify with @ryanemerson or @pruivo that using tokens (which might eventually expire) is the way
* Verify that updating a token is sufficient or identify other steps that are necessary (like restarting the operator)
* Update our scripts to use tokens that are valid for at least 48 hours
* Update the documentation to use longer tokens, and provide a operational procedure to update the tokens based on the items above.

**Comment by pruivo** [comment]
I wasn't aware that the tokens in OCP4 had an expiration time. I probably should have used [a secret](https://docs.openshift.com/container-platform/4.14/nodes/pods/nodes-pods-secrets.html#nodes-pods-secrets-creating-sa_nodes-pods-secrets) to create the token. I'm surprised users have not reported this yet... :shrug:

**Comment by ahus1** [comment]
Follow-up: https://github.com/infinispan/infinispan-operator/issues/1965
