### ISSUE TITLE
Support for keycloak 23.x.x

### ISSUE THREAD

**Issue by tommasobrunowork** [keycloak/keycloak-benchmark#676]
### Description

I would like to the cadence of scheduling support for new keycloak versions.

Is there a plan to make the benchmark compatible with the new keycloeak versions?

### Motivation

We currently use keycloak benchmark and keycloak 21.x.x and would like to upgrade keycloak to the latest versions.

**Comment by kami619** [comment]
@tommasobrunowork Thanks for raising this, this is on the back burner for a while now, will try to bring it up with the team, if we can do more frequent releases thus ensuring the compatibility for different Keycloaks. For your purpose, the latest main from keycloak-benchmark should be compatible with the Keycloak develop latest, as we are running the CI tests from here - https://github.com/keycloak/keycloak-benchmark/actions/runs/7484458726/workflow
