### ISSUE TITLE
Horreum report mixes CPU limit and request

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#701]
### Describe the bug

The report puts on of the deployment parameters to the wrong target, see: 

> jq -n --arg cpu_limit "{{ .KC_CPU_REQUESTS }}"...

This results in 

```
"cpuLimitPerPod": 6,
```

Where it should be `cpuRequestedPerPod`. 

Please check

### Version

main

### Expected behavior

For CPU, report both requested and limit

### Actual behavior

Reporting requested as limit.

**Comment by ahus1** [comment]
@andyuk1986 - could you please have a look? Once this is fixed, please also update the old data for the runs in the `result-data` branch.

Thanks!

**Comment by andyuk1986** [comment]
@ahus1  Thanks for reporting this. Sure, will do.

**Comment by andyuk1986** [comment]
@ahus1 a question: the KC_CPU_LIMITS variable  is set by default to empty string. But as far as I understand, in case it is set , it is will have a numeric value. So I wanted to ask, how do you want to show it in JSON in case it is not set - as null or empty string as well (I think 0 is not an option or yes)?

**Comment by ahus1** [comment]
@andyuk1986 - as you suspected, "0" is not an option. If it is not set, it is unbounded. In the JSON, use it as a number or null if not set.

**Comment by andyuk1986** [comment]
PR sent: https://github.com/keycloak/keycloak-benchmark/pull/703
