### ISSUE TITLE
Timeout and failure detection tuning guide

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak-benchmark#708]
### Description

I've talked to Bela and I'm having second thoughts about it. We are optimizing for an edge case that may or may not happen and 99% of the time, everything will be fine. It may be a waste of resources sending heartbeats every second just to save some seconds from the detection time (during my test, the default timeouts took ~40s longer to detect and correct itself).

I agree we should have a (tunning) guide explaining all these concepts so users can make decisions on how they want to tolerate faults. Just remember, there is no such thing as a free lunch, there is always a cost 👍

Another concern is if we want to do the same tunning in Keycloak cluster. I do not want to do 1-on-1 mapping of JGroups attributes into CLI options 😱 😨

**Comment by ahus1** [comment]
A first part of it was started here #714? 
cc: @mhajas
