### ISSUE TITLE
Join group scenario

### ISSUE THREAD

**Issue by artur-baltabayev** [keycloak/keycloak-benchmark#78]
### Description

This addition to the benchmark covers the group assignment case. It will create a user and assign him to a group.

### Motivation

We had a request to test if Keycloak handles group assignments in a reasonable time frame on systems with a lot of groups and roles.

### Details

Pull Request : https://github.com/keycloak/keycloak-benchmark/pull/77

**Comment by kami619** [comment]
closed by #77
