### ISSUE TITLE
why do you use Keycloak

### ISSUE THREAD

**Issue by HelloTo4x** [keycloak/keycloak-benchmark#79]
### Description

Hi, can u tell me why u use Keycloak instead of Spring security, which feature does it have but Spring security doesn't have it ?

**Comment by ahus1** [comment]
This is a question for either stackoverflow or the keycloak user's mailing list. Therefore I close this issue. 
https://www.keycloak.org/community

**Comment by HelloTo4x** [comment]
can u explain me. i don't understand this on stackoverflow

**Comment by ahus1** [comment]
Here's the website of stackoverflow: https://stackoverflow.com/
