### ISSUE TITLE
For persistent sessions, deploy Infinispan with maxCount memory setting in user/client sessions cache

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#805]
### Description

Once persistent sessions are enabled, not all entries need to be in memory for Keycloak.

The same should be done for the external Infinispan, where also only a subset should be kept in memory.

### Discussion

https://github.com/keycloak/keycloak/pull/29347

### Motivation

Don't exhaust Infinispan's memory.

This is already in the docs. To make sure that it works this should be part of the scripts in the KCB project.

**Comment by mhajas** [comment]
We should also change the number of owners to 1 for all four session caches to be on par with the HA guide.https://github.com/keycloak/keycloak/blob/main/docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
