### ISSUE TITLE
Daily scheduled cluster deletion job fails

### ISSUE THREAD

**Issue by andyuk1986** [keycloak/keycloak-benchmark#810]
### Describe the bug

The delete cluster job is failing with error on the first picked cluster which causes that the rest available clusters are not deleted.

### Version

main

### Expected behavior

The delete cluster job should delete all clusters which are not marked with "keepalive" flag.

### Actual behavior

The job fails in the end of the first picked cluster deletion making impossible to go forward and delete the rest available clusters.

**Comment by andyuk1986** [comment]
The issue is fixed with PR #811

**Comment by ahus1** [comment]
@andyuk1986 - please only close the issue once the PR is merged. If you add `Closes #xxx` to the description of the PR, it will close the issue automatically if the PR is merged. I'm therefore re-opening the issue.

**Comment by andyuk1986** [comment]
Thanks @ahus1
