### ISSUE TITLE
Fix rosa failure to edit scaling machinepool

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak-benchmark#821]
### Describe the bug

After the latest rosa cli release there is an error when updating machinepool:
```
Failed to update machine pool 'scaling' on hosted cluster 'gh-keycloak-a': Attribute 'autoscaling.max_replica' must be provided
```

whole run 
https://github.com/keycloak/keycloak-benchmark/actions/runs/9153748946/job/25163835069

To work around this issue rosa cli was downgraded to version 1.2.38.

We should solve this issue and revert back to latest rosa version.

### Version

main

**Comment by ryanemerson** [comment]
This is fixed in ROSA `v1.2.40-rc1`, so we should be able to revert https://github.com/keycloak/keycloak-benchmark/commit/f0d092d7faf72a453f7917d8dbefce7a219e1959 once `v1.2.4.0` is officially released.
