### ISSUE TITLE
Update loadbalancing documentation to detail the various Route53 tasks

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak-benchmark#826]
### Description

Currently `installation-route53-loadbalancer.adoc` details how to create Route53 loadbalancers using various `*.sh` scripts directly. As we provide Route53 tasks in our `provision/cross-dc/Taskfile.yaml`, we should update the documentation to use these as it simplifies the steps required.

**Comment by ahus1** [comment]
We've moved to AWS Global Loadbalancers, and we don't plan to update Route 53 things so much and eventually remove them. So I'd argue this doesn't add much value, therefore closing it.
