### ISSUE TITLE
Increased GC overhead in the continuous performance tests 

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#827]
### Describe the bug

Increased GC overhead in the continuous performance tests

### Version

Keycloak 25

### Expected behavior

We want the GC behavior to be consistent.

### Actual behavior

In some cases the CPU utilization of one of the pods gets skewed in terms of utilization.
While the JVM reports 2.5% overhead, the overall CPU usage of the pod doubles.

### How to Reproduce?

TBA

**Comment by ahus1** [comment]
With https://github.com/keycloak/keycloak/issues/29939 being resolved, IMHO this issue can be closed.

**Comment by kami619** [comment]
Correct @ahus1 I think with https://github.com/keycloak/keycloak/issues/29939 resolved, we could close this one out. I have created a new Epic #839 to look into other possible JVM GC controls for G1GC and group them with https://github.com/keycloak/keycloak-benchmark/issues/781 for the next series of tests and documenting the run-book, metrics of relevance.
