### ISSUE TITLE
Horreum: Add field to environment data to differentiate between deployment types

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak-benchmark#862]
We need to add a field to the environment json at deploy time so that Horreum is able to differentiate results based upon deployment type.

https://github.com/keycloak/keycloak-benchmark/blob/main/provision/common/Taskfile.yaml#L78-L114 

To prevent the passing of yet more env variables, a possible solution is to move the creation of the json file to a callable Task which can then be executed as part of  `provision/rosa-crossdc` `task` or `task active-active` executions.

**Comment by kami619** [comment]
@ryanemerson `--argjson is_multi_az "{{ .MULTI_AZ }}"` could we not just make this a deployment type field instead of a boolean value ?

**Comment by ryanemerson** [comment]
I think that could work. We would need to add a check to the `.status` of the task to ensure that the file is rewritten when this field changes. At the minute, I think going from an active-passive -> active-active run will not cause the file to be updated.

**Comment by kami619** [comment]
Ok, great, I will work on that change and create a PR once I am back from the PTO.

**Comment by ahus1** [comment]
No longer needed as due to #900 the number of scenarios has been reduced so that we can distinguish them.
