### ISSUE TITLE
Add Create, Read and Delete scenarios for Authz Entity

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#89]
### Description

Add Create, Read and Delete scenarios for Authz Entity

### Motivation

This is being done in order to support the testing of the new storage layer performance tests and compare it with the legacy storage layer

### Details

The implementation would be to enable Authorization for numerous clients and then create custom resources and permissions within the Authorization for specific client to be able to populate the Authz Entity Store

**Comment by ahus1** [comment]
@kami619 - I've received a draft from Hynek which entities are important, and it turns out that none AuthZ entities has a priority. Therefore I wonder if this issue should be closed for now.

**Comment by kami619** [comment]
Ok, I will close it for now and may be re-open it later when we need it.
