### ISSUE TITLE
Analyze timeout in daily run

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#896]
Daily run times out after some hours.

Revisit `async: 86400` to make it configurable, so the GitHub runner doesn't time out and we have the results archived.

**Comment by kami619** [comment]
I am still tackling the other CI issues I encountered to fix the `rosa-cli-setup` step, hence got delayed getting to this issue.

**Comment by kami619** [comment]
https://github.com/kami619/keycloak-benchmark/commit/2f3b77865f4711131dfd307d3a0c180fd32e7e35 - Updated the default timeout of the Ansible polling to 60 mins and increased the polling interval to 60 secs.

**Comment by kami619** [comment]
this issue is fixed with the OCP downgrade. Do we still want to make the timeout configurable @ahus1 ?

**Comment by ahus1** [comment]
Seems be resolved with rollback to OpenShift 4.14.x
