### ISSUE TITLE
Make the daily test run on A/A + persistent sessions like we plan this for KC26

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#900]

**Comment by kami619** [comment]
@ahus1 

Question on the Acceptance criteria,

Do we want just this `ROSA Scheduled Create Active/Active cluster with Persistent Sessions` or a combination of this and the `ROSA Scheduled Create Active/Active cluster with External Infinispan`?

**Comment by ahus1** [comment]
As agreed in today's meeting: Keep the two scenarios:

1. ROSA Scheduled Create Active/Active cluster with Volatile Sessions and External Infinispan
2. ROSA Scheduled Create Active/Active cluster with Persistent Sessions and External Infinispan
