### ISSUE TITLE
compare A/A performance results with A/P tests

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#901]

**Comment by ahus1** [comment]
@kami619 - can you please have a look at the response times as well?

**Comment by kami619** [comment]
@ahus1 Yup, I will look at endpoint response times and the throughput across the tests for different deployment types. I will share the results in this thread.

**Comment by kami619** [comment]
cpuUsageForCredentialGrantsTest

- Irrespective of the HA type (A/A or A/P) when persistentSessionsEnabled is set to true, we saw 100% increase in the `Client credentials grant type` endpoint's 50% response time compared with when persistentSessionsEnabled is set to `false` in the deployment context.
- Throughput remains the same across the deployment types.
- `credentialGrantsPerSecPer1vCpu` remains the same across the deployment types, with a 5% variance between the deployments.

**Comment by ahus1** [comment]
@kami619 - those percentages look scary, still if they occur on a low initial response time, they might be considered ok. Can you please update the previous comment to include the absolute time in milliseconds to capture this perspective? Thanks!

**Comment by ahus1** [comment]
Great insights from those performance tests! 
I will look into the client credential grant increased response times later today as those times shouldn't increase as it shouldn't use persistent user sessions by default. There seems to be a potential for an optimization.

**Comment by kami619** [comment]
[rosa_scalability_runs_comparision.zip](https://github.com/user-attachments/files/16390815/rosa_scalability_runs_comparision.zip)
Here is the data dump which I used for the analysis.

**Comment by kami619** [comment]
@ahus1 I made a mistake in the `cpuUsageForCredentialGrantsTest` analysis when I said the endpoint response times spiked when `persistentSessionsEnabled` is set to true, that was not a correct observation. I have updated the statement to reflect the actual data.

**Comment by kami619** [comment]
@ahus1 Here is the outcome from the re-run of the comparison tests for CPU Logins test.

### **User Logins Per Second Per 1vCPU Per Pod**

| Scenario | External Infinispan | Persistent Sessions | Logins per Sec | Delta (%) |
|----------|---------------------|---------------------|----------------|-----------|
| A/A      | True                | False               | 53             | Baseline  |
| A/A      | True                | True                | 49             | -7.55%    |
| A/P      | False               | False               | 46             | -13.21%   |
| A/P      | False               | True                | 49             | -7.55%    |
| A/P      | True                | False               | 52             | -1.89%    |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions leads to a **7.55% decrease** in login rate.
- **A/P Scenario:**
  - Without external Infinispan, persistent sessions increase the login rate by **6.52%**.
  - Enabling external Infinispan results in a **13.04% increase** compared to the A/P baseline without persistent sessions.

---

### **Response Time Percentiles (1st Percentile)**

#### **1. Browser Posts Correct Credentials**

| Scenario | External Infinispan | Persistent Sessions | 1st Percentile Response Time (ms) | Delta (%) |
|----------|---------------------|---------------------|-----------------------------------|-----------|
| A/A      | True                | False               | 74                                | Baseline  |
| A/A      | True                | True                | 109                               | +47.30%   |
| A/P      | False               | False               | 89                                | +20.27%   |
| A/P      | False               | True                | 114                               | +54.05%   |
| A/P      | True                | False               | 74                                | 0.00%     |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions results in a **47.30% increase** in response time.
- **A/P Scenario:**
  - Without external Infinispan and persistent sessions, the response time increases by **20.27%**.
  - Enabling both features results in the same performance as the A/A baseline.

#### **2. Browser Logout**

| Scenario | External Infinispan | Persistent Sessions | 1st Percentile Response Time (ms) | Delta (%) |
|----------|---------------------|---------------------|-----------------------------------|-----------|
| A/A      | True                | False               | 14                                | Baseline  |
| A/A      | True                | True                | 22                                | +57.14%   |
| A/P      | False               | False               | 27                                | +92.86%   |
| A/P      | False               | True                | 32                                | +128.57%  |
| A/P      | True                | False               | 13                                | -7.14%    |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions increases response time by **57.14%**.
- **A/P Scenario:**
  - Enabling both features causes a **92.86% increase** compared to the baseline.
  - Disabling persistent sessions and enabling external Infinispan leads to a **7.14% decrease** in response time.

---

### **Key Takeaways**

1. **User Logins Per Second:**
   - **Persistent Sessions:** Generally reduces login rate across both A/A and A/P scenarios.
   - **External Infinispan:** Enhances login rate, especially noticeable in the A/P scenario with a **13.04% improvement**.

2. **Response Time Percentiles:**
   - **Persistent Sessions:** Increases response times significantly, particularly for browser post credentials and logout operations.
   - **External Infinispan:** Improves performance, showing zero to negative deltas when enabled without persistent sessions.

3. **Performance Trade-offs:**
   - While persistent sessions offer state management benefits, they come with performance overhead.
   - External Infinispan provides substantial performance improvements, especially when persistent sessions are not enabled.

**Comment by kami619** [comment]
@ahus1 Here are the re-run results comparing A/A and A/P deployments of Keycloak in Multi-site.



### **User Logins Per Second Per 1vCPU Per Pod**

| Scenario | External Infinispan | Persistent Sessions | Logins per Sec | Delta (%) |
|----------|---------------------|---------------------|----------------|-----------|
| A/A      | True                | False               | 53             | Baseline  |
| A/A      | True                | True                | 49             | -7.55%    |
| A/P      | False               | False               | 46             | -13.21%   |
| A/P      | False               | True                | 49             | -7.55%    |
| A/P      | True                | False               | 52             | -1.89%    |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions leads to a **7.55% decrease** in login rate.
- **A/P Scenario:**
  - Without external Infinispan, persistent sessions increase the login rate by **6.52%**.
  - Enabling external Infinispan results in a **13.04% increase** compared to the A/P baseline without persistent sessions.

---

### **Response Time Percentiles (1st Percentile)**

#### **1. Browser Posts Correct Credentials**

| Scenario | External Infinispan | Persistent Sessions | 1st Percentile Response Time (ms) | Delta (%) |
|----------|---------------------|---------------------|-----------------------------------|-----------|
| A/A      | True                | False               | 74                                | Baseline  |
| A/A      | True                | True                | 109                               | +47.30%   |
| A/P      | False               | False               | 89                                | +20.27%   |
| A/P      | False               | True                | 114                               | +54.05%   |
| A/P      | True                | False               | 74                                | 0.00%     |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions results in a **47.30% increase** in response time.
- **A/P Scenario:**
  - Without external Infinispan and persistent sessions, the response time increases by **20.27%**.
  - Enabling both features results in the same performance as the A/A baseline.

#### **2. Browser Logout**

| Scenario | External Infinispan | Persistent Sessions | 1st Percentile Response Time (ms) | Delta (%) |
|----------|---------------------|---------------------|-----------------------------------|-----------|
| A/A      | True                | False               | 14                                | Baseline  |
| A/A      | True                | True                | 22                                | +57.14%   |
| A/P      | False               | False               | 27                                | +92.86%   |
| A/P      | False               | True                | 32                                | +128.57%  |
| A/P      | True                | False               | 13                                | -7.14%    |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions increases response time by **57.14%**.
- **A/P Scenario:**
  - Enabling both features causes a **92.86% increase** compared to the baseline.
  - Disabling persistent sessions and enabling external Infinispan leads to a **7.14% decrease** in response time.

---

### **Key Takeaways**

1. **User Logins Per Second:**
   - **Persistent Sessions:** Generally reduces login rate across both A/A and A/P scenarios.
   - **External Infinispan:** Enhances login rate, especially noticeable in the A/P scenario with a **13.04% improvement**.

2. **Response Time Percentiles:**
   - **Persistent Sessions:** Increases response times significantly, particularly for browser post credentials and logout operations.
   - **External Infinispan:** Improves performance, showing zero to negative deltas when enabled without persistent sessions.

3. **Performance Trade-offs:**
   - While persistent sessions offer state management benefits, they come with performance overhead.
   - External Infinispan provides substantial performance improvements, especially when persistent sessions are not enabled.

**Comment by kami619** [comment]
Results for the Client Credentials grant scenario


### **Credential Grants Per Second Per 1vCPU**

| Scenario | External Infinispan | Persistent Sessions | Credential Grants per Sec | Delta (%) |
|----------|---------------------|---------------------|---------------------------|-----------|
| A/A      | True                | False               | 613                       | Baseline  |
| A/A      | True                | True                | 609                       | -0.65%    |
| A/P      | False               | False               | 533                       | -13.05%   |
| A/P      | False               | True                | 625                       | +1.96%    |
| A/P      | True                | False               | 621                       | +1.31%    |

**Observations:**
- **A/A Scenario:** Enabling persistent sessions results in a slight **0.65% decrease** in credential grants.
- **A/P Scenario:**
  - Without external Infinispan, persistent sessions increase grants by **17.26%** compared to the A/P baseline without persistent sessions.
  - Enabling external Infinispan results in a **16.52% increase** compared to the A/P baseline without external Infinispan.

---

### **Response Time Percentiles (1st Percentile)**

| Scenario | External Infinispan | Persistent Sessions | 1st Percentile Response Time (ms) | Delta (%) |
|----------|---------------------|---------------------|-----------------------------------|-----------|
| A/A      | True                | False               | 12                                | Baseline  |
| A/A      | True                | True                | 12                                | 0.00%     |
| A/P      | False               | False               | 9                                 | -25.00%   |
| A/P      | False               | True                | 9                                 | -25.00%   |
| A/P      | True                | False               | 9                                 | -25.00%   |

**Observations:**
- **A/A Scenario:** Response times remain unchanged with persistent sessions enabled.
- **A/P Scenario:**
  - All A/P configurations result in a **25.00% decrease** in response time compared to the A/A baseline.

---

### **Key Takeaways**

1. **Credential Grants Per Second:**
   - **A/A Scenario:** Minimal impact from persistent sessions.
   - **A/P Scenario:** Both persistent sessions and external Infinispan increase credential grants, with external Infinispan providing a **16.52% improvement** compared to A/P without it.

2. **Response Time Percentiles:**
   - A/P configurations consistently achieve better response times, with a **25.00% improvement** compared to the A/A baseline.

**Comment by ahus1** [comment]
Follow-up issue created: #926 

cc: @kami619, @pruivo
