### ISSUE TITLE
Grafana URL not set when creating a snapshot

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#95]
### Describe the bug

The Grafana URL is showing "localhost" when creating a snapshot, should be the host name used in the ingress. 

Also, creating an external snapshot should be disabled until we have a private instance for that. 

### Version

0.7-SNAPSHOT

**Comment by ahus1** [comment]
@kami619 - I accidentially pushed this to main directly, this should work now. If not, please let me know.

**Comment by kami619** [comment]
The specific change works just fine, but for some reason the cadvisor based metrics are failing to be scraped at Prometheus layer. I am not 100% sure, if this is related to this change, but this seems to broken very recently.

![image](https://user-images.githubusercontent.com/3415105/174641608-3f5fb95f-a6a4-42c2-bbfd-ef928b3b06fe.png)

**Comment by kami619** [comment]
thanks for fixing it along with #99

**Comment by kami619** [comment]
the changes look good to me now.
