### ISSUE TITLE
Upgrade to OpenShift 4.16

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#952]
```[tasklist]
### Tasks
- [x] Upgrade to 4.16.x
- [x] Verify the secrets lifecycle and age
- [x] Verify if the Scaling benchmark executes properly - TASK FAILED
```

**Comment by kami619** [comment]
When the load test ran, things didn't look good. https://github.com/kami619/keycloak-benchmark/actions/runs/10600673186/job/29378692196 The original issue with the erratic behavior of CPU and Benchmark was back.

![Screenshot 2024-08-28 at 13 38 45](https://github.com/user-attachments/assets/cb9c655a-6799-49c5-ac2c-c64d3a1bc364)

![Screenshot 2024-08-28 at 13 39 22](https://github.com/user-attachments/assets/adff21fd-c7bf-4e74-b3ef-feb57fd936a6)

**Comment by mhajas** [comment]
@kami619 I see you are observing secrets in `runner-keycloak` namespace, however, if I remember correctly the secrets were also created in other namespaces. Were you able to check those as well? 

You can do the following to observe if new secrets are created k9s:
1. On the secrets page you already have press 0 to see secrets from all namespaces
2. Press shift + a to sort the list by age

Then you will be able to see all new secrets on top of the page.
